### ISSUE TITLE
Unable to build (Dockerfile not working)

### ISSUE THREAD

**Issue by delijati** [ubports/morph-browser#10]
The provided `Dockerfile` is not working. I also tried the one from `clickable` but there seams `QtWebEngine` to be missing. Can you please **update** the` Dockerfile` and the `README`.

**Comment by balcy** [comment]
the one from clickable did work for me, at least for the phone (not yet for the desktop)
now for the click to build you need to set `option(CLICK_MODE "Build as a click package" on)` in CMakeLists.txt.
I think it is no longer recommend to use the click for morph (while I used it for testing, I even "masked" an apparmor error of content hub, that was working fine with my click package, but not for the deb-based morph)
so closing this issue now
