### ISSUE TITLE
Unable to upload files to webpages

### ISSUE THREAD

**Issue by nikita-veshchikov** [ubports/morph-browser#102]
I cannot upload photos since the last update.
My actions to reproduce the behavior on BQ 4.5:
1) Open facebook.com
2) Click on the form with a new post, press on the button to upload a photo
3) Choose form (for the application) opens on the phone
4) .. whatever app I click on, nothing happens (File Manager, Gllery, Camera)

**Comment by balcy** [comment]
Hi thank you for the report, are you on stable ? The it is a known issue that is solved on RC

**Comment by balcy** [comment]
https://github.com/ubports/morph-browser/issues/51

**Comment by nikita-veshchikov** [comment]
Hi, yes, I am using the latest stable version (the one that comes with auto update).

**Comment by UniversalSuperBox** [comment]
Duplicate of #51, fixed in `devel` and `rc`.
