### ISSUE TITLE
Browser crashes when operating selection boxes in staged mode in landscape

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/morph-browser#108]
This is a difficult bug to report, simply due to its absurdity.

`morph-browser` crashes right after opening a second window for selection boxes in some cases. These cases follow:

* Always on the Nexus 7 2013 when in landscape mode (never in portrait, even with scaling set low)
* On the Nexus 5 in landscape mode, if the GRID_UNIT_PX environment variable is set to 20 or below
* On the Fairphone 2 in landscape mode, if the GRID_UNIT_PX environment variable is set to 20 or below
* On the Bq M10 FHD when in landscape mode

The logs from each device I have when the crash occurs follow:
* Fairphone 2: [1](https://paste.ubuntu.com/p/2sNXYQhrzJ/), [2](https://paste.ubuntu.com/p/yG7YkQqD3h/), [3](https://paste.ubuntu.com/p/V8S8DMPZdX/)
* Nexus 5: [1](https://paste.ubuntu.com/p/sbsJ7spXNh/), [2](https://paste.ubuntu.com/p/9q89xnsWdv/)
* Nexus 7: [1](https://paste.ubuntu.com/p/QksVwnj7Nx/)

All logs were taken on a single session for each device. The random nature of the error addresses leads me to think we have a dangling pointer somewhere. The incredibly specific nature of its reproducibility upsets me.

**Comment by UniversalSuperBox** [comment]
Interesting to note, further investigation reveals that similar errors occur when the browser exits normally. The segfault may not be related to the selection box.

**Comment by zubozrout** [comment]
Well, actually I've just experienced something similar but thought it was a network related issue. I was just in a train running through a tunnel and was offline for a minute. In that I've oriented my mobile (arale, latest devel) to landscape, scrolled through the site a bit but in a few seconds the browser just crashed.

I wanted to open a new ticket but this sounds fairly similar so I suspect it could be the same issue.

[morph.log](https://github.com/ubports/morph-browser/files/2778138/morph.log)

**Comment by 10JML01** [comment]
BQ M10 FHD; rc
Unity crash and reload when selecting the selection field (mostly when more tabs are open) after closing the not reacting new window.
Try here: https://www.snowboarden.de/tipps-und-tricks/snowboardlaenge-bestimmen.html

Edit: Even more trouble when you enter something in the field below and then press the selection field with the keyboard still open.

**Comment by Flaburgan** [comment]
I had that bug several times with the Fairphone 2 even in portrait mode.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/morph-browser/pull/273
