### ISSUE TITLE
Circular dependency in determining user agent

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/morph-browser#109]
Morph has a bit of a problem with morphing right now, which somehow seems to be made worse by #89. I started fixing it [here](https://github.com/ubports/morph-browser/tree/xenial_-_useragent-cirle) but quickly found that we have a much worse issue than addressing the wrong object.                     

In order to [determine our user agent](https://github.com/ubports/morph-browser/blob/99c0bb559a2261669374de6d5225e695ee7eb8dc/src/Morph/Web/UserAgent02.qml#L71), we need to know our [screen size](https://github.com/ubports/morph-browser/blob/99c0bb559a2261669374de6d5225e695ee7eb8dc/src/Morph/Web/UserAgent02.qml#L67), [as generated here](https://github.com/ubports/morph-browser/blob/99c0bb559a2261669374de6d5225e695ee7eb8dc/src/Morph/Web/plugin.cpp#L131). Due to the way that this code works, we can't know our screen size until after we have a valid focused window for Morph. We can't have a valid focused window for Morph until after we have a user agent set (since the user agent is taken at the time that `MorphWebContext` is instantiated, `MorphWebView` depends on `MorphWebContext`, etc.).

This doesn't cause any visible problems now, but with the fix listed above (or #89, apparently), the default (desktop) user agent is always assumed for the first tab which loads in a browser session. 

Maybe we should try to get the user-agent reset in [init](https://github.com/ubports/morph-browser/blob/99c0bb559a2261669374de6d5225e695ee7eb8dc/src/app/webbrowser/morph-browser.qml#L31) just prior to loading the first tabs.

**Comment by Flohack74** [comment]
I am still voting for having the state of the phone (mobile, converged) reported by the OS, so that we do not need to look at sizes or orientation at all. It would be quite easy to do IMHO

**Comment by UniversalSuperBox** [comment]
It is. The size of the screen is returned by Qt, just not until after the application has initialized.

**Comment by UniversalSuperBox** [comment]
Well, I think I should leave my efforts to fix this for now. We might consider acting like other mobile browsers and set desktop mode per-site rather than globally. That would allow us to check the override setting at a more appropriate time.
