### ISSUE TITLE
tab shadow is longer than the tab

### ISSUE THREAD

**Issue by pixelr0** [ubports/morph-browser#11]
open 2-3 tabs, swipe from the buttom to see all the tabs. the shadows are longer than the tabs

![next](https://user-images.githubusercontent.com/333589/41711013-bdce08b2-754f-11e8-95b0-57f416f9255c.png)

**Comment by kugiigi** [comment]
The issue seems to be in the file `TabChrome.qml`.
From my observation, the scaling behavior of the image in the BorderImage seems to be different from before. I got a workaround but when I tested in a different GU setting, the shadow doesn't fit well again.
