### ISSUE TITLE
No reload button?

### ISSUE THREAD

**Issue by vandys** [ubports/morph-browser#113]
Don't know if I'm just missing it, but there really needs to be a "reload page" button.
The only way I've found to get this effect is to select the location on the location bar,
then tap again to make it go to a single position cursor, then drag to the end and
hit enter.

**Comment by balcy** [comment]
If I click in the current URL, I have a reload button on the left, and it is possible to use Enter on the on screen keyboard as reload too. (I'm on RC though)

**Comment by vandys** [comment]
Great, works for me.  Thanks!
