### ISSUE TITLE
Broken link without error

### ISSUE THREAD

**Issue by cibersheep** [ubports/morph-browser#118]
Device: m10 HD Xenial RC
Steps: go to a inexistent url (for example: http://www.aceadventuregames.com/ this link desn't exist anymore)
Behaviour: weird blank page with three buttons?
Expected: Error message saying «Link couldn't be opened» or similar

**Images**

Morph:
![imatge](https://user-images.githubusercontent.com/6640041/49330284-af4bb100-f58c-11e8-9df7-8ecf55fa06a7.png)

Oxide:
![imatge](https://user-images.githubusercontent.com/6640041/49330280-a6f37600-f58c-11e8-87dc-7d3ea2a74d0e.png)

(«Network error. It seems that you are having problems to show _link_. Check your connection and try to load the page again»)

**Comment by advocatux** [comment]
Yep, it doesn't show an external error but fwiw the 'internal' error is:

`qml: [JS] (chrome-error://chromewebdata/:4696) Uncaught ReferenceError: jstProcess is not defined`

**Comment by UniversalSuperBox** [comment]
Hmm, are both of these from the same network at the same time? Some DNS providers will redirect to advertisement pages when you request a site that doesn't exist.

**Comment by balcy** [comment]
I confirm that I see the "strange page" for (not existing) www.ubports1234.com as well. (and my DNS provider does not redirect the page)
On the same network desktop browsers show the proper message "trouble connecting to ..."

**Comment by balcy** [comment]
~I think we can use https://doc.qt.io/qt-5/qml-qtwebengine-webengineview.html#loadingChanged-signal for that~ no longer sure, because Browser already is set to display the error sheet for "WebEngineView.LoadFailedStatus"

**Comment by cibersheep** [comment]
> Hmm, are both of these from the same network at the same time? Some DNS providers will redirect to advertisement pages when you request a site that doesn't exist.

If I understood correctly: I confirm that both screenshots are from the same wifi connection. One on Oxide on Vivid, the other on Morph on Xenial RC

Later I can test on mobile data if it's of any help...

**Comment by jezek** [comment]
FP2 (2019-W09)
In morph browser after opening non-existent page (www.ubports1234.com), only a blank (white) page with one grayish button with tranlated "Refresh page" text is shown. No other text or error messages.

EDIT: this behaviour was observed with SuruDark theme. For default Ambiance theme, the text is shown properly. See 2nd comment below.

**Comment by UniversalSuperBox** [comment]
@jezek, which language are you currently using? This is the page in en_US:

![image](https://user-images.githubusercontent.com/21966173/53649655-41a13680-3c08-11e9-8604-0d6036d49fcc.png)

**Comment by jezek** [comment]
@UniversalSuperBox my languge is sk_SK.
Now, I've tested it with en_US. Gone to "System Settigs -> Language & Text -> Display Language" and selected "English (United States)" and restarted phone.
After visiting a non-existen page, the same happens:
![screenshot20190301_171040211 resized 25](https://user-images.githubusercontent.com/5408235/53650639-446e4c80-3c45-11e9-9964-fed0b7815112.jpg)

EDIT:
This seems to be an theming issue. On Ambiance theme and both languages (en_US, sk_SK) the network error as in your picture is shown.

So on default Ambiance theme it works. ~~(On SuruDark, there seems to be a font color issue, but this is not a part of this bug)~~

**Comment by UniversalSuperBox** [comment]
Ah, that might be related to your dark theme. Could you file a new issue about not being able to see the error page with a dark theme?

**Comment by haeckle** [comment]
Fixed on Nexus 4 with 2019-W09

**Comment by erik-kueng** [comment]
FP2
2019-W09
could not reproduce this issue
