### ISSUE TITLE
layout / zoom is really big on aquaris m10 cooler

### ISSUE THREAD

**Issue by Trim** [ubports/morph-browser#12]
Hello,

I've installed 16.04 W26 this week and the browser-ng from the Open Store on an aquaris m10 (cooler) tablet.

When I open any page with browser-ng, the layout of the page is like if I've zoomed "1000 %".
I think that works well on mobile phone, but on a large screen as tablet that's a bit hard to use.

Note that, I can zoom in even more, but I can't zoom out to have a smaller layout :)

Thanks for the good job !

_Edit_

For example, this page, give such layout:

![github on cooler](https://cloud.adorsaz.ch/index.php/s/zgaYqD7da8ZCzty/download)

**Comment by cyberpunkedu** [comment]
Zoom is even bigger on Nexus 5 :octopus: 
![browserng](https://user-images.githubusercontent.com/3128635/46187120-e359db80-c296-11e8-8728-cf92feed9120.png)

**Comment by Billdemoncho** [comment]
same, with my meizu pro 5.
Which solution to change the size and characters?

**Comment by ruedigerkupper** [comment]
Confirming for Nexus 5 (hammerhead) after update to OTA-5. Scaling is really, REALLY large, see screenshot by userj. I can zoom even larger, but not smaller than that.

**Comment by advocatux** [comment]
@ruedigerkupper the big scaling issue happens in Next (browser-ng), not in Morph. Are you sure you are using the right one? I'm asking because I was confused too the first time after the upgrading, because even the icons are the same.

**Comment by cyberpunkedu** [comment]
Indeed this is not an issue in Morph.

**Comment by Billdemoncho** [comment]
Hello on my Meizu pro I only use Morph and here is the size of the screen which is not big enough. And I had the same problem with Next
![screenshot20181013_154832927](https://user-images.githubusercontent.com/42817545/46906205-3e7b0780-cf00-11e8-8466-0525baeb0f1e.png)

**Comment by UniversalSuperBox** [comment]
@userj, @ruedigerkupper, is this an issue with the Morph Browser built in to OTA-5?

**Comment by UniversalSuperBox** [comment]
@Billdemoncho, can you file that as a separate issue please?

**Comment by cyberpunkedu** [comment]
> @userj, @ruedigerkupper, is this an issue with the Morph Browser built in to OTA-5?

I don't have this issue in OTA-5, but I also was testing Morph in the QA stage, so I installed it manually. At that time it didn't have a problem either.

**Comment by UniversalSuperBox** [comment]
Okay. Morph appears to have fixed this issue. If you still have Browser Next installed, you can safely remove it.

**Comment by ruedigerkupper** [comment]
Ouch, right you are. I thought browser-ng had literally become Morph, but they are separate projects. All seems fine in Morph. Sorry for the confusion.

**Comment by Trim** [comment]
Well, I've opened this bug on browser-ng repository. So I suppose project team has renamed the project as morph-browser later ;)
