### ISSUE TITLE
Cannot inject custom js in webapps

### ISSUE THREAD

**Issue by mymike00** [ubports/morph-browser#124]
I have a plain webapp (no qml at all, I have `Exec=webapp-container` in the `.desktop` file) and a file called `webapp-properties.json` which calls a custom script.
the code in this custom script was executed with oxide, but not anymore with morph

**Comment by cibersheep** [comment]
There's a workaround and is using a qml with a webview and embed the js as a UserScript
In the import area you could:
```import Morph.Web 0.1
import QtWebEngine 1.7 as Oxide
```

And in a Page element
```
WebContext {
	id: webcontextIF

        userScripts: [
            Oxide.WebEngineScript {
                id: cssinjection
                injectionPoint: WebEngineScript.DocumentCreation
                sourceUrl: Qt.resolvedUrl("js/cssinjection.js")
                worldId: WebEngineScript.MainWorld
            }
	]
}
```

And the webview:
```
WebView {
	id: webview

	context: webcontextIF
	url: 'https://whatever'
}
```

**Comment by mymike00** [comment]
Thanks, I'll try that workaround, but I highly prefer not using qml in simple webapp like mine...

**Comment by balcy** [comment]
do you have an example of an app using it ? I've found hints to webapp-properties.json in the source code of morph, but not understood how the properties really work.

**Comment by mymike00** [comment]
my `.desktop` has
```
Exec=webapp-container --webappModelSearchPath=. --store-session-cookies --webappUrlPatterns=https?://www.mywebsite.com/* https://www.mywebsite.com/mypath %u
```
`.apparmor` is
```
{
    "template": "ubuntu-webapp",
    "policy_groups": [
        "keep-display-on",
        "networking",
        "webview"
    ],
    "policy_version": 1.3
}
```
then I have a file called `webapp-properties.json`
```
{
    "includes": ["https://www.mywebsite.com:*/*"],
    "name": "ExtendedWebappProperties",
    "scripts": ["myscript.js"],
    "domain":"",
    "homepage":""
}
```
and obviously a script called `myscript.js`

**Comment by UniversalSuperBox** [comment]
Closed via #140

**Comment by Fuseteam** [comment]
This was appearently broken with the removal of oxide

**Comment by balcy** [comment]
not with the removal of oxide, but it depended on "Ubuntu.UnityWebApps" which was removed in https://github.com/ubports/morph-browser/commit/18d38c8ecb050f1e2313e46e153da413cf4545be#diff-0f082207c5919dab491e1030b99f9d8104f6f39d20ecf791924303a33b3bc31e while we moved from Qt 5.9 to Qt 5.12 (the Qt version of the system, not the one of QtWebEngine)

As a replacement we could use a new parameter "--user-scripts=..." to the webapp-container as done in https://github.com/ubports/morph-browser/pull/527

The file webapp-properties.json would then no longer be needed.

in the current example "--user-scripts=myscript.js" would be used.

**Comment by Fuseteam** [comment]
ah i see; that sounds like a plan forward yeah, thanks!
