### ISSUE TITLE
Second window reopens when starting Morph after closing all of its tabs

### ISSUE THREAD

**Issue by myii** [ubports/morph-browser#130]
#### Related issue

This bug has some overlap with #35 as well.

UPDATE: As mentioned at the bottom, I reckon this might be another symptom of #35 and not a separate bug.

#### Description of bug

Conversation from the [main Telegram group](https://t.me/ubports):

> jon robson, [24.12.18 11:41]
> Morph browser is opening 3 scopes. Any one else experiencing this?
> 
> advocatux, [24.12.18 11:51]
> [In reply to jon robson]
> What do you mean?
> 
> jon robson, [24.12.18 12:14]
> [In reply to advocatux]
> When I open a morph scope and pull back into scope mode, there are three scopes open woth morph browser written underneath.
> 
> Rodney, [24.12.18 12:26]
> Not scopes. Those are windows, and it's an app. :)
> 
> jon robson, [24.12.18 12:33]
> I assume none of you are having this problem. OTA6 on fp2.
> 
> jon robson, [24.12.18 12:34]
> Only getting it in morph browser.
> 
> advocatux, [24.12.18 12:52]
> [In reply to jon robson]
> No, I don't have that issue. I checked it on edge & rc channels.
> Have you tried to reset Morph settings?
> You can also try to remove Morph's cache, data, and config files using UT Tweak tool if the other "solution" doesn't work
> 
> jon robson, [24.12.18 13:06]
> [In reply to advocatux]
> Reset with tweak tool sorted it! Thanks
> 
> myii, [24.12.18 13:17]
> [In reply to jon robson]
> Had a similar problem on my N5. Started after opening a tab in a new window. The second window kept opening up every time I opened Morph after that.
> 
> myii, [24.12.18 13:18]
> [In reply to advocatux]
> Thanks for that(!). Clearing the application data was sufficient.
> 
> myii, [24.12.18 13:22]
> OK, it's reproducible. Open a link in a new window. Trying to close the final tab in either window closes both windows. Then both windows keep opening up when starting Morph again.
> 
> advocatux, [24.12.18 13:27]
> [In reply to myii]
> Hmm it doesn't happen to me. Do you have the "restore the previous session" checked in Morph Settings?
> 
> advocatux, [24.12.18 13:28]
> Okay, I tested with that option "on" and I see that behaviour too
> 
> advocatux, [24.12.18 13:28]
> but it doesn't happen when it isn't checked
> 
> myii, [24.12.18 13:28]
> It shouldn't persist the window that is closed.

#### Steps to reproduce

As mentioned above but for clarity:

1. Ensure `Restore previous session at startup` is selected
1. Start with a single window, single tab
1. Open a link in a new window
1. Close the tab for the new window (this triggers #35)
1. Reopen Morph and both windows open including the tab that was closed
1. (Clear application data with UTTT)

#### Multiple windows

In fact, I can confirm this happens if there are multiple windows, like Jon Robson mentioned in the discussion.  Closing the one tab in any window triggers #35 and all of the windows reopen.  In one of my tests, Unity 8 also restarted.

#### Expected outcome

Beyond #35, the window which has its last tab closed should not reopen.  Actually, while writing this, it seems apparent that this is just another side-effect of #35.  If that is resolved, I wouldn't be surprised if this issue becomes redundant.

**Comment by advocatux** [comment]
Device: Nexus 5 (hammerhead)
Channel: RC
Version: `2018-W01` (_really_ `2019-W01`)

Fix works. I can't reproduce this issue anymore.

**Comment by 10JML01** [comment]
BQ E5HD and M10FHD
rc
2018-W01

Fix works. I guess the problem was #35

**Comment by erik-kueng** [comment]
Fairphone 2
rc
2018-W01

Fix works. I can not reproduce the issue.
