### ISSUE TITLE
Initial page of webapps cannot be loaded sometimes

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#133]
In the current xenial branch, but in the PR branch xenial_-_loadfailed, too, the following problem exists:
Steps:
- open a webapp
- close it after it is fully loaded
- start it again after some seconds
Problem:
- the error sheet (Network error) appears
- when tapping refresh the webapp loads successfully
For me this problem is more likely to happen on Wifi connection
So far I've not seen the problem for local html apps.

I think those at not network errors but rather the problem of the webapp container startup, maybe a race condition.

**Comment by jezek** [comment]
FP2 (2019-W09)
Trying to reproduce bug on [Ubuntu One Webapp](https://open-store.io/app/ubuntuone.matcher). Webapp opens/closes multiple times without error.

**Comment by mattbel10** [comment]
I tried opening and closing several times the Youtube webapp by Mateo Salta and I cannot reproduce the described issue, therefore it is fixed. Thank you.

Device: Meizu Pro5
Build: Ubuntu 16.04 (2019-W09)

**Comment by erik-kueng** [comment]
FP2
2019-W09
could not reproduce this issue

**Comment by ziggutas** [comment]
Nexus 7 flo 2019-W09
Could not reproduce this issue despite repeated attempts with OMG!ubuntu! Webapp
