### ISSUE TITLE
Morph doesn't properly support system themes for tabs headers

### ISSUE THREAD

**Issue by mattbel10** [ubports/morph-browser#142]
- Device: Meizu Pro 5

- Channel: 16.04 Devel

- Build: 2019-01-24

**Steps to reproduce**
Go to UT Tweak Tool and select a theme different from the default "Ambiance" (either SuruDark or SuruGradient). 

**Expected behavior**
The Morph browser app is expected to get the theme appropriately for each piece of the window.

**Actual behavior**
Instead, the SuruDark theme causes the disappearance of the cross used to close each open tab (look at the attached picture for the sake of clarity).

![screenshot20190119_112016290](https://user-images.githubusercontent.com/34881626/51792946-fcc55280-21b8-11e9-9c6a-29bcd145fb78.png)

**Comment by 10JML01** [comment]
Same for BQ E5hd (vegetahd)  and BQ M10FHD (frieza) in the current rc. A good dark theme support is important and can be easier on the eyes and battery.

**Comment by ziggutas** [comment]
Suru dark theme selected in UTTT on Nexus 7 flo (2019-W-09). When viewing list of tabs in Morph Browser the 'close tab' crosses are all visible

**Comment by jezek** [comment]
FP2 (2019-W09)

viewing tabs in morph browser:
- theme SuruDark - crosses visible
- theme SuruGradient - crosses visible ~~(thus the theme itself is somewhat weird, but this is not part of this bug)~~

**Comment by mattbel10** [comment]
I cannot reproduce anymore the described issue, therefore it is fixed thanks to @dobey.

Device: Meizu Pro5
Build: Ubuntu 16.04 (2019-W09)

**Comment by haeckle** [comment]
Fixed on Nexus 4 with 2019-W09 (tested with SuruDark and SuruGradient)

**Comment by erik-kueng** [comment]
FP2
2019-W09
could not reproduce issue, tested with SuruDark and SuruGradient)
   - in SuruGradient the "finished" button in the tab-screen can not be read
