### ISSUE TITLE
Feature: Allow to start browser in private mode

### ISSUE THREAD

**Issue by ilya-bystrov** [ubports/morph-browser#145]
It would be nice to be able to start browser in private mode.
I prefer such way of using browsers, for instance, cookies are not stored between sessions.

**Comment by balcy** [comment]
the good news is that the command line flag for the private mode does already exist:
`morph-browser --desktop_file_hint=/usr/share/applications/morph-browser.desktop --incognito`
so we could add an additional icon for it, or maybe open it in private mode, if the last closed window was in that mode

**Comment by mateosalta** [comment]
[private.zip](https://github.com/ubports/morph-browser/files/2820043/private.zip) Made a quick click with an icon - just shortcuts to the browser like you mentioned balcy - but only needs unconfined since it is launching a command outside of it

**Comment by balcy** [comment]
cool thanks! Maybe another possibility is to put an entry 'start in private mode' to the settings.

**Comment by cibersheep** [comment]
I vote for the settings option

**Comment by gbdomubpkm** [comment]
I would like to re-emphasize, in my user opinion, the importance of this feature request discussed with Tim Sueberkrueb as part of his Webber application : https://github.com/timsueberkrueb/webber/issues/14 https://github.com/timsueberkrueb/webber/issues/13
Thank you

**Comment by balcy** [comment]
ok I would then put an option "start in private mode" to "Settings -> Privacy & Permissions" (as first item)

if the user has set a homepage (custom or start.duckduckgo.com), should it appear when the browser is started in incognito mode ? (currently that is not the case)
Or we can make it so that if morph is started with the inconito icon / `--incognito` command, the homepage is not shown (no change to how it is now), but when started normally, but has the new setting "start in private mode" = true the hompage is shown.

If the user ticks "start in private mode", the setting "restore session on startup" would be set to false, and the "restore session on startup" checkbox remain disabled.

**Comment by gbdomubpkm** [comment]
Hello.
Thank you for reactivating this request.

I rephrase according to my point of view:
- An option'' start in private mode'': very good!!
- When this option is set to ON: 
  . either the home page is loaded 
    automatically (start.duckduck...) when morph- 
    browser is launched directly ;
  . or any other link launched on a page 
    web, by a webapp or an app opens 
    in private mode.
  . the opening of a new private window 
    opens, as now, a window to 
    empty.

- When this option is OFF, the current actions in place are executed 

I agree with your paragraph on recovery at startup.

**Comment by balcy** [comment]
ok so one point still to clarify is how the homepage (if the user has set one) is handled with this new mode on the startup of morph.

variant | morph started with `--incognito` flag | morph started normally, user setting "always start in private mode" is active
--- | --- | ---
current implementation | homepage is not shown | n.a. (setting does not yet exist)
variant (1) | homepage is shown | homepage is shown
variant (2) | homepage is not shown | homepage is shown
variant (3) | homepage is not shown | homepage is not shown

**Comment by gbdomubpkm** [comment]
According to my ideas and if I understand the table well, I think that v(2) reflects my point of view as a user but I do not transpose in it all my exposed situations.

**Comment by balcy** [comment]
@UniversalSuperBox I've forgot to ask: do you think rather variant 1 (current PR) or variant 2 is better ? The disadvantage of 2 is that it behaves differently for the --incognito flag than for the setting.
The advantage is that current behavior is kept. On the other hand I think the --incognito flag is rather never used on the phone, therefore we can keep variant 1, too.
