### ISSUE TITLE
Problems with custom URL schemes (e.g. for telegram)

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#147]
Currently there is a problem with some pages that make requests to custom URL schemes without user interaction.
Example: https://t.me/ubports/176342

The page will end up flickering with the URL chrome-error://chromewebdata/

The default policy for unknown schemes is to allow them when initiated via user interaction, but not to allow them for other cases. (like the policy for popup windows)

https://doc.qt.io/qt-5/qml-qtwebengine-webenginesettings.html#unknownUrlSchemePolicy-prop

The easiest solution to that would be adding 
`settings.unknownUrlSchemePolicy: WebEngineSettings.AllowAllUnknownUrlSchemes`
to WebViewImpl.qml

But I'm not sure if we intend this for morph... (in this case opening the example URL would immediately open the telegram app, or switch to it if it is already open)
Another thing I've tried is to catch this specific error in the loadingChanged event:
in Morph/Web/MorphWebView.qml I've added the following at the beginning of onLoadingChanged:
```
 if (loadRequest.errorCode === 420) {
    _webview.stop()
    return
 }
```
with that the example page does open, and the telegram app would only open if you click on "VIEW IN GROUP".
But with that the example page does not always show the post:
![image](https://user-images.githubusercontent.com/848115/52376837-6ff58100-2a63-11e9-895b-93377b99d8d9.png)
Sometimes it will display like on the left, sometimes like on the right. (so the user has to refresh the page to see the post)
This problem does not appear, if we change the policy as written above

**Comment by balcy** [comment]
my original thought was to change the policy, but then add a block or user confirm for "non user initiated" requests in morph.
But that does not work, because https://doc.qt.io/qt-5/qml-qtwebengine-webenginenavigationrequest.html does not have a property "userInitiated" (like for example https://doc.qt.io/qt-5/qml-qtwebengine-webenginenewviewrequest.html has).
The navigationType is 0 (WebEngineNavigationRequest.LinkClickedNavigation) for both the initial load of the page, and the user click on the "VIEW IN GROUP" button.

**Comment by UniversalSuperBox** [comment]
It might be possible to determine if the user started the navigation using the [navigationType enum](https://doc.qt.io/qt-5/qml-qtwebengine-webenginenavigationrequest.html#navigationType-prop), no?

**Comment by UniversalSuperBox** [comment]
Sorry, I can't read. Sorry.

**Comment by balcy** [comment]
are there security concerns with allowing those protocols even if not user initiated ? E.g websites could open the telegram / telephony app without user interaction.
Maybe we could block them completely by default, and make a user setting to allow all.
I haven't found out why it does reload the error page all the time.

**Comment by zubozrout** [comment]
Hi,
I've just experienced this issue on this page: "https://www.seznamzpravy.cz/clanek/kontrolori-odhalili-v-praze-nelegalni-bourarnu-masa-67136". At least I expect it is the same issue.

[application-legacy-morph-browser-.log](https://github.com/ubports/morph-browser/files/2920441/application-legacy-morph-browser-.log)

It loads correctly and shortly after the loading progress bar disappears (after the page is loaded I presume) it starts displaying a blank screen, sometimes displaying a network error warning over it (which is quite hard to catch on a screenshot as it only flickers over for a short time and in uneven periods)

<p align="center">
<img src="https://user-images.githubusercontent.com/3088349/53654774-ddee2c00-3c4e-11e9-951c-fd35c64b00ca.png" width="180" alt="screenshot20190301_181502765" style="display: inline-block">
<img src="https://user-images.githubusercontent.com/3088349/53654780-e0508600-3c4e-11e9-8911-409fb5587ed4.png" width="180">
<img src="https://user-images.githubusercontent.com/3088349/53654781-e181b300-3c4e-11e9-93e2-404c2e95bb9f.png" width="180">
</p>

1. First screenshot: almost on load, same soon after load
2. After crash: blank screen
3. After crash: error message visible, mostly only for a few milliseconds

Device: arale (Meizu MX4)
Build: devel revision 2019-02-27

**Comment by ziggutas** [comment]
Devices: flo and krillin on rc (2019-W41/2)
Admit I don't really understand how to test this issue, but fwiw the link posted by zubozrout above opens correctly on both of these devices

**Comment by zubozrout** [comment]
I can confirm the link I've posted earlier now works. And I have not seen that issue for a while now. So either it got fixed somewhow or I've been lucky and the `seznamzpravy.cz` url was updated as well.
