### ISSUE TITLE
open downloaded items in browser

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#148]
Currently the downloaded items (downloads page) have the following user interactions:

- normal click / tap : "Open with" menu (content hub) opens, file can be opened with another app
- long press: enable "select mode", which allows to delete multiple downloads

Especially for webpages downloaded as HTML, but for text and multimedia files as well, it would be useful to open them directly in the browser after downloading, or at some point later.
Moreover it could be useful to copy the path or the *file://...* url of the downloaded file to the clipboard.

So the question would be how could this be integrated to the downloads menu.

Possible solution (1)
- normal click / tap : "Open with" menu (content hub) opens, file can be opened with another app
- long press: show dialog:
  - open with other app
  - open in browser
  - copy path
  - copy file url
  - edit items

Possible solution (2)
- normal click / tap : show dialog:
  - open with other app
  - open in browser
  - copy path
  - copy file url
- long press: enable "select mode", which allows to delete multiple downloads

or something else ?

**Comment by balcy** [comment]
@cibersheep maybe you know what might be a good solution

**Comment by cibersheep** [comment]
The first thing that comes into mind is a trailing action bar:
- normal click / tap : contenthub this should add the browser as a target app
- long press: enable "select mode", which allows to delete multiple downloads
swipe to the left to show: 
  - copy path
  - copy file url

What do you think?

**Comment by balcy** [comment]
yes sounds good I think! Have to look into how it could work with the content hub.

**Comment by cibersheep** [comment]
^__^ it's adding the proper urldispatcher info to morph and some code when it opens it up :)
It could create an endless quantum loop
