### ISSUE TITLE
save domain specific settings

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#154]
I'd suggest to add another data model (like BookmarksModel), that saves domain specific settings.

For each domain (if not using incognito mode) the following could be saved:

- custom zoom level (if not using the default zoom), see https://github.com/ubports/morph-browser/issues/107
- a flag that indicates if custom URL schemes are allowed (user is prompted when a page wants to use a custom url scheme), see https://github.com/ubports/morph-browser/issues/147
- ~~possibly a custom user agent string and / or desktop mode flag, see https://github.com/ubports/morph-browser/issues/109#issuecomment-441133462~~
- permissions (e.g. always allow location / audio for this page)
- ...

This should not be done for all domains / visited pages, but only for each domain with settings other than the default.

The settings should be cleared when the user deletes the browser history.
Possibly in the settings menu single entries could be removed / edited, too.

**Comment by Flohack74** [comment]
Would that be also possible for WebApp containers? I have a container for public transport and I have to give permission for location every time again, its annoying ;)

**Comment by balcy** [comment]
I think so. If the webapp container can access the database and we assume the setting is valid for all webapps and morph-browser.
