### ISSUE TITLE
Non-Suru main menu icons

### ISSUE THREAD

**Issue by cibersheep** [ubports/morph-browser#156]
«View source» and «Save as HTML/PDF» icons in main menu doesn't follow Suru look
Here you have a «view source» candidate.
[codesvg.zip](https://github.com/ubports/morph-browser/files/2897313/codesvg.zip)

For the save option, I would use icon named «save-as»
.

**Comment by balcy** [comment]
ok thanks for the suggestions

For "View Source" I would then use "text-xml-symbolic" (that is already available on the phones)

![text-xml-symbolic](https://user-images.githubusercontent.com/848115/53372199-8603ac80-3952-11e9-945d-eee65ff322d1.png)

The "Save as" does look very similar to the downloads icon ("save") though:

![save](https://user-images.githubusercontent.com/848115/53372496-4e493480-3953-11e9-8429-d1cb30d6dd46.png) "save"

![save-as](https://user-images.githubusercontent.com/848115/53372520-599c6000-3953-11e9-98b1-56ee92bf3a01.png) "save as"

how about the following for the html / PDF export:
![x-office-presentation-symbolic](https://user-images.githubusercontent.com/848115/53372615-a2541900-3953-11e9-8990-1fe88eb17b43.png) "x-office-presentation-symbolic"

or we use "save as" for the export, and the following for the downloads:
![save-to](https://user-images.githubusercontent.com/848115/53372685-cca5d680-3953-11e9-971c-1672cc4677eb.png)  "save-to"

**Comment by cibersheep** [comment]
I think the only on I wouldn't use is the x-office-presentation-symbolic :)
You decide, I'll support you :)

**Comment by mateosalta** [comment]
I like "save as" for the pdf, as it has the lines for the document on the right, save to looks like a file list or picture list that fits for downloads. Like it :)
