### ISSUE TITLE
Page crashes

### ISSUE THREAD

**Issue by osimmasgard** [ubports/morph-browser#160]
Hi,

I am running version

morph-browser/xenial,now 0.24+ubports+0~20190209195217.44~1.gbp22ec9b armhf [installed,automatic]

and have quite ofgen page crashes, the page turns white. When this happens I see this in the log of Morph:

QObject::startTimer: Timers cannot be started from another thread

**Comment by kugiigi** [comment]
@osimmasgard Is this still happening? Also, the description is a bit vague to be honest.

**Comment by osimmasgard** [comment]
Hi, you can close this as it is old and I can no longer verify the existence of this problem.

Thanks!
