### ISSUE TITLE
[feature request] implement delete cookies option

### ISSUE THREAD

**Issue by Danfro** [ubports/morph-browser#163]
As far as I know cookies are stored in the sqllite database at: `.local/share/morph-browser/cookies`.
There is no option in morph browser to view and/or remove cookies

I really would like to have an option to remove them from within morph browser.
I would think settings/privacy would be a good place where to put that option.
Ideally one could view existing cookies and delete them all/individual. To start with an "clear all cookies" option would be good.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/morph-browser/pull/260

**Comment by Danfro** [comment]
E5 RC. Confirmed, morph now does have a "clear all cookies" option.

**Comment by jonnius** [comment]
Confirmed on FP2, RC.

**Comment by cibersheep** [comment]
N5 RC, works:
- browse to a web ask to store cookies
- accept them
- delete them with Morpho
- go back to the website

It will ask to accept cookies again

**Comment by Bolly** [comment]
BQFHD RC, works:

- browse to a web ask to store cookies
- accept them
- delete them with Morph
- go back to the website

It will ask to accept cookies again
