### ISSUE TITLE
Using SuruDark theme, error texts are not visible

### ISSUE THREAD

**Issue by jezek** [ubports/morph-browser#164]
Device: FP2 (2019-W09)

Steps to reproduce:
- Using [UT Tweak Tool](https://open-store.io/app/ut-tweak-tool.sverzegnassi) select SuruDark theme & restart Unity8
- Open new, non-existent page in morph browser (eg. www.ubports1234.com)

Expexted behaviour:
- error message is show, like picture in https://github.com/ubports/morph-browser/issues/118#issuecomment-468712686

Current behaviour:
- error message text is not visible, like picture in https://github.com/ubports/morph-browser/issues/118#issuecomment-468719770

**Comment by mattbel10** [comment]
Confirmed the behaviour also on my phone: with SuruDark only one button is displayed with description in italian "Aggiorna la pagina" (refresh page) but with Ambiance the correct network error message is displayed.

Device: Meizu Pro5
Build: Ubuntu 16.04 (2019-W09)

**Comment by 10JML01** [comment]
Works in 2019-W16 (rc) on BQ M10 FHD.

**Comment by mariuszkliber** [comment]
Same here, works in 2019-W18 on BQ M10 FHD.

**Comment by jezek** [comment]
FP2 (2019-W18)
Works.

**Comment by ziggutas** [comment]
BQ E4.5 rc (2019-W18)
Cannot reproduce the issue.

**Comment by ziggutas** [comment]
Nexus 7 (flo) rc (2019-W18)
Works
