### ISSUE TITLE
Context dialog in Incognito window opens in the main window

### ISSUE THREAD

**Issue by kugiigi** [ubports/morph-browser#167]
## Steps to reproduce
1. Open Morph browser
2. Open an Incognito window/tab
3. Load a page.
4. Press and hold a link in the page

## Expected Result
A context menu is displayed showing options such as "Open in new tab" and "Open in new window"

## Actual Result
The incognito window doesn't show anything as if it's not reacting to the press and hold gesture but if you switch to the main non-incognito window, you'll see that the context dialog is displayed there instead.

**Comment by balcy** [comment]
yes confirmed.
Even requests, if the page (in private mode) can access the microphone, do appear on the not private page.

**Comment by njtwiseman** [comment]
Confirmed I see it

**Comment by jezek** [comment]
FP2 (2019-W18)
Cotext menu is displayed properly in incognito window.

**Comment by ziggutas** [comment]
BQ E4.5 rc (2019-W18)
Context menu displays ok

**Comment by ziggutas** [comment]
Nexus 7 (flo) rc (2019-W18)
Context menu displays ok
