### ISSUE TITLE
Fullscreen for html5 video broken

### ISSUE THREAD

**Issue by mateosalta** [ubports/morph-browser#17]
How to reproduce:
- visit site like youtube.com
-play video
-hit fullscreen button in media contols

What happens - nothing
What should happen - media goes fullscreen, and navigation disappears, along with top bar

Research:

http://doc.qt.io/qt-5/qml-qtwebengine-fullscreenrequest.html
https://doc.qt.io/qt-5.11/qml-qtwebengine-webenginesettings.html#fullscreenSupportEnabled-prop
https://stackoverflow.com/questions/43078450/how-to-make-qwebengineview-go-fullscreen-qt-5-8
https://codereview.qt-project.org/#/c/74279/5/examples/widgets/widgetsnanobrowser/widgetwindow.cpp

examples:
https://doc.qt.io/qt-5.11/qtwebengine-webengine-quicknanobrowser-example.html

**Comment by balcy** [comment]
https://github.com/ubports/browser-ng/pull/16
is now included in PR

**Comment by mateosalta** [comment]
nice
