### ISSUE TITLE
debug browser, inspector mode

### ISSUE THREAD

**Issue by lduboeuf** [ubports/morph-browser#179]
hello,

Just tried to launch `ubuntu-app-launch morph-browser --inspector` and access remote debugging with http://192.168.1.79:9221/ on chromium but nothing happens. Is this feature still exist ?

**Comment by balcy** [comment]
I have not tried that yet, but the following command worked for me (with the IP address of my phone):
`QTWEBENGINE_REMOTE_DEBUGGING=192.168.1.79:9221 morph-browser --desktop_file_hint=/usr/share/applications/morph-browser.desktop https://duckduckgo.com`
(the start URL argument is optional)
https://stackoverflow.com/a/29721197/4326472

**Comment by lduboeuf** [comment]
oh right, i will test it thanks. I will update documentation if needed.
