### ISSUE TITLE
Opening a context menu seems to cause morph-browser to lose focus

### ISSUE THREAD

**Issue by JulianGro** [ubports/morph-browser#192]
Opening a context menu seems to cause morph-browser to lose focus.

Steps to reproduce:
Go to a website with a link.
Open the context menu on the link by holding your finger on it
Press any button in the context menu
You will now have to press on the browser before you can scroll or open a new context menu again.

What should happen:
You should be able to scroll or click directly after closing a context menu.

**Comment by balcy** [comment]
what I've found out so far is, that the error seems to be already present in QtWebEngine itself.

If in WebViewImpl.qml the function `onContextMenuRequested: function(request)` is removed, or `return;` is put as its first line, you still have the effect that you need to click once on the browser, and only then it is possible to scroll again.

~~It is like the "real" / native context menu, which is not visible, took away the focus and is closed upon the click.~~ [edit: speculation]

So it is not related to the dialogs / context menus shown by the morph browser.

**Comment by balcy** [comment]
ok, I think the real cause was code in MorphWebView that was catching onContextMenuRequested as well.

**Comment by ziggutas** [comment]
BQ E4.5 rc (2019-W41/2)
I cannot reproduce this issue

**Comment by mgns-gh** [comment]
FP2 RC (2019-W41/2)
The Context menu seems to work as expected. 
I cannot reproduce the issue described.
