### ISSUE TITLE
Chrome-error   chromewebdata

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/morph-browser#195]
You can try this : 

Go to https://leboncoin.fr to see an advertisement.

Try to see the phone number of the vendor in pressing the blue  phone number zone.

![screenshot20190610_000824814](https://user-images.githubusercontent.com/50362604/59165297-d8d82d00-8b19-11e9-887d-4f523f6dfc16.png)

You must see very fleetingly the phone number but just after the screen sparkle to see a white chromewebdata page and through a black network error page : problems to display : chrome-error://chromewebdata/.

![screenshot20190610_000949480](https://user-images.githubusercontent.com/50362604/59165309-02915400-8b1a-11e9-9072-9088e879154a.png)
![screenshot20190610_000943219](https://user-images.githubusercontent.com/50362604/59165312-1472f700-8b1a-11e9-9677-5c906cd0ca9a.png)

**Comment by balcy** [comment]
thanks for the report, it is a problem with custo url schemes (in this case tel:)
https://github.com/ubports/morph-browser/issues/147

**Comment by gbdomubpkm** [comment]
Indeed, you right ! Since i wasn't sure and there could be nuances for this annoying bug,  better two reports than zero ! 🙂
