### ISSUE TITLE
Enhancement, remove adverts.

### ISSUE THREAD

**Issue by Thieb67k** [ubports/morph-browser#197]
hello, 
wouldn't it nice to fight against all kind of advert that appear and take too much space on the screen?
thanks.

**Comment by niutech** [comment]
This could be generalized to support web extensions, including AdBlock / uBlock Origin.

**Comment by mateosalta** [comment]
there is uadblock in openstore

**Comment by Thieb67k** [comment]
Indeed. I tried it and looks quite good. Thanks.
