### ISSUE TITLE
block / whitelist domains

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#200]
while doing some debugging I showed a message box for all requests of a webapp.
Many requests came from 3rd party domains. With a desktop browser and an addon like noscript you can easily block the ones not needed for just using the site normally.
I thought it would be useful to have control about them in morph, too.
With the "DomainPermissions" it is possible to block domains, or even opt in to a "whitelist mode" that requires each domain to be confirmed once.

**Comment by ziggutas** [comment]
Devices: Nexus 7 (flo), BQ E4.5 ubuntu edition. Both on rc (2019-W42)
Blocking domains, whitelist mode works as expected on these devices
