### ISSUE TITLE
Text selection (like in the old browser ?)

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#21]
Would it be possible to have a text selection like with the Oxide based browser with the browser-ng based on QtWebEngine ?
![textselection](https://user-images.githubusercontent.com/848115/44362577-b4935d00-a4c1-11e8-9a02-234de0d2729d.jpeg)

I've thought about several possibilities, but have not yet come to a conclusion.

What I already do know: the [ContextMenuRequest](https://doc.qt.io/qt-5/qml-qtwebengine-contextmenurequest.html) contains the x and y coordinate of the control the event was sent from.
And it is possible to get the corresponding DOM element via [JavaScript.](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/elementFromPoint)

https://github.com/component/textarea-caret-position/blob/master/index.js allows to calculate the coordinates of the caret, the selection start, and selection end. 

So I see the following possibilities:
1) draw QML rectangles for the selection, and update their position with the text selection, if the users moves them, adapt the text selection via JavaScript. This needs to take into account the browser scrolling position, zoom and that not all of the text might be visible
2) in an "select mode" just let the user select the text (like for example in the terminal app) without the rectangles
3) In "select mode" the content of the control is copied to a QML TextAera, the user can select the text there, and later it is copied back to the original control
4) Make a feature request to QtWebEngine, that a future version supports configurable touch selection control (like Oxide)

I'm not really sure we can provide the same user experience without controlling the backend (oxide) here. E.g. at least 1) feels to be a very "fragile" implementation, because you are not really bound to the text, but rather to coordinates here...

**Comment by Fuseteam** [comment]
the third possibility seems to give the best control while the second feels better integrated
the 4th is probably the most integrated option

**Comment by lduboeuf** [comment]
i miss oxide selection too :). Hope someone can work on it.

**Comment by mateosalta** [comment]
https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-59999 might be the upstream bug

**Comment by gbdomubpkm** [comment]
Not being able to select the area we want to copy and paste after is more than annoying in everyday use. Is there a possible solution now ?

**Comment by fredldotme** [comment]
Current status on this is that we run into an Internal Compiler Error when building the Skia parts of QtWebEngine on armhf. This requires either help from Canonical and/or patching GCC ourselves.

Current QtWebEngine 5.13 status: https://github.com/ubports/qtwebengine-opensource-src-packaging/tree/xenial_-_webengine-5-13
The ICE we currently hit: https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1838419

**Comment by flaun** [comment]
seems to be very complicated...
still someone working on it or simply not possible to fix it at the moment?

**Comment by lduboeuf** [comment]
i've heard kugiigi is working on it
