### ISSUE TITLE
[feature request ?] Video player

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/morph-browser#222]
This is more a questionning than a priority request strictly speaking (unless you could make it happen relatively easily) : could a multi-format video player be implemented in Morph-browser and used efficiently on the basis of an offline mode to present another video player option in UT on all phones including NEXUS 5 which has few options?
In other words, could Morph-browser be used efficiently as a video player?
Thank you in advance for your answer.

**Comment by UniversalSuperBox** [comment]
Hi there,

Yes, the browser can serve to play videos on your device. I believe this is what the UTmedia app does already.

Since this is a request to create an app and not a feature, I'll close this now.
