### ISSUE TITLE
User-Agent Chromium Version outdated

### ISSUE THREAD

**Issue by maytinhdibo** [ubports/morph-browser#223]
The chromium version on UBports is outdate. I hove ubports team will change user agent on browser to use message on facebook.com (link window phone).

**Comment by fredldotme** [comment]
Current status on upgrading QtWebEngine/Chromium is that we run into an Internal Compiler Error when building the Skia parts of QtWebEngine on armhf. This requires either help from Canonical and/or patching GCC ourselves.

Current QtWebEngine 5.13 status: https://github.com/ubports/qtwebengine-opensource-src-packaging/tree/xenial_-_webengine-5-13
The ICE we currently hit: https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1838419

**Comment by maytinhdibo** [comment]
@fredldotme what about "user agent"  :/

**Comment by fredldotme** [comment]
Newer Chromium should have a newer User Agent also.

**Comment by UniversalSuperBox** [comment]
The user agent for Morph is set in https://github.com/ubports/morph-browser/blob/xenial/src/Morph/Web/UserAgent02.qml. This is taken from the QtWebEngine release, which was closest to Chromium 65 for QWE 5.11, which we are using: https://github.com/qt/qtwebengine/blob/5.11/dist/changes-5.11.0. Qt then backports security fixes from newer releases of Chromium.

It's worth noting that Qt 5.11 is no longer supported, so it is very important to upgrade past it.
