### ISSUE TITLE
Get back to a blank home page

### ISSUE THREAD

**Issue by ghost** [ubports/morph-browser#236]
To reproduce this bug:
Go to the Settings page
In Home Page, type a website (for example https://ubports.com)
Save
Then reopen Home Page and clear the URL to get back to a blank home page

Bug:
Once the URL is void, it is impossible to click on the Save button

Expected behavior:
The Save button is accessible even when the home page URL is void
In this case, a blank page is defined as the home page

**Comment by balcy** [comment]
yes that sounds reasonable.
