### ISSUE TITLE
Cookies management in private mode

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/morph-browser#238]
BQ E5 HD  RC  V60

How should cookie management behave in private mode at the moment ?
Some time ago, it seems to me that cookies, in private mode, were not registered, which was the purpose. For some time now, there has been the creation of a cookie file, which does not seem normal to me.

**Comment by balcy** [comment]
are you on devel or RC ? 
Then it is probably a duplicate of https://github.com/ubports/morph-browser/issues/237

**Comment by gbdomubpkm** [comment]
Thank you for your answer.
I wanted to check before rewriting. I wasn't sure it was the same bug that 237  but indeed and for what I understand, this bug seems to have been fixed by the update 2019-W42 corresponding to the partial termination of https://github.com/ubports/morph-browser/issues/237 . I no longer see any appearance of the cookies file in.local/share/morph-browser.

**Comment by gbdomubpkm** [comment]
I checked out this point  :  new window (offTheRecord is false for all windows !)
using http://inloop.github.io/sqlite-viewer/#. I see indeed cookies.
As it known by  https://github.com/ubports/morph-browser/issues/237 , i close the issue.
