### ISSUE TITLE
Pulldownmenus in webpages are incorrect

### ISSUE THREAD

**Issue by tux4us** [ubports/morph-browser#239]
16.04 edge

When open a pulldownmenu from a webpage, the menu is to undersized to show all items. Menu don't adjust to numbers of items in menu.

**Comment by balcy** [comment]
I think this issue could be moved to unity8
[edit: or mir ?]
see https://github.com/ubports/morph-browser/issues/54 for reference

**Comment by lduboeuf** [comment]
or related to QtWebEngine ?

**Comment by lduboeuf** [comment]
![66077182-bdc57900-e55f-11e9-8694-e5670bed69e5](https://user-images.githubusercontent.com/11663835/67748134-821cb280-fa2a-11e9-82cd-0016200a1be8.png)

**Comment by lduboeuf** [comment]
Don't know if this can be fixed soon on Mir or QtWebEngine  ?
If not, can't we provide a js hook for `select` tags, and convert them to html elements stylable with css ?

**Comment by Stefano0101** [comment]
Can confirm this is happening on all of my UT devices, Meizu Pro 5, Nexus 7 , ( Port Oneplus3t) on Egde channel, now after merge also on Devel.

**Comment by giiba** [comment]
Switched to Devel channel to check out the new edge interface, but this issue is going to force me to switch back as it leaves the browser crippled for most sites that I encounter with drop boxes. The previous functionality was glitchy but I could at least proceed through online banking (for example).

**Comment by giiba** [comment]
Switched to Devel channel to check out the new edge interface, but this issue is going to force me to switch back as it leaves the browser crippled for most sites that I encounter with drop boxes. The previous functionality was glitchy but I could at least proceed through online banking (for example).

On a OPO latest devel build.

**Comment by giiba** [comment]
This seems to be a problem with the html form input 'select' tag, for a ready example see: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_elem_select

Screenshot:
![screenshot20191103_100040082](https://user-images.githubusercontent.com/7121141/68089733-dfe13e00-fe20-11e9-8a01-3e4f8c03ffc7.png)



This doesn't seem to effect dropdowns done through javascript as those are working; see: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_js_dropdown

**Comment by giiba** [comment]
![screenshot20191103_094301874](https://user-images.githubusercontent.com/7121141/68089634-baa00000-fe1f-11e9-9c09-f6f1f1218a9c.png)

We cannot blame this on qtwebengine or the new mir, as shown above the 'select' tag works as expected in Demo Browser from the app store.

**Comment by lduboeuf** [comment]
so seems to be a morph issue, what are the diffs between demo-browser and morph ?

**Comment by giiba** [comment]
It also works as expected in an OGRS web app:

![screenshot20191103_161010795](https://user-images.githubusercontent.com/7121141/68094465-79c2de00-fe55-11e9-8b24-20b538230685.png)

**Comment by giiba** [comment]
I don't know what it means, but every time I open the pull down from w3schools I see an error in the log:

"qt.qpa.mirclient attempted to deliver an event to a non-existent window, ignoring"

**Comment by zubozrout** [comment]
Well, actually it would be nice for Morph to implements something more mobile/touch friendly than even working but tiny select box like that. Android browsers usually do things like this I'd guess:
https://img.gadgethacks.com/img/original/10/48/63659054965129/0/636590549651291048.jpg

That would also fix the issue even without the need to debug this :), though I think it would still be nice to have this fixed anyway in case any other popup windows (whatever that may be) cause the same issue.

_([image source](https://android.gadgethacks.com/how-to/google-chrome-101-unlock-material-design-2-user-interface-with-round-icons-blended-status-bar-0184092/))_

**Comment by giiba** [comment]
Digging into Demo Browser, I see that it bundles a binary called qtwebbrowser; so I have no idea if it working has any bearing on Morph.

I have however found that morph based web apps also throw the error I listed in my last post, every time a select list is called by touching it.

**Comment by gbdomubpkm** [comment]
@balcy
Please can you check this.
And i am not sure if it is a bug and the same bug :
Tested only with OTA-11.

A very short time ago in gitlab,  dekkan/dekko/tickets, for a new bug report, in a scrolling menu, I could choose 'no template'. Now it's impossible. I still have a template even if i don't want.

Thank you very much and congratulations for your excellent work

**Comment by balcy** [comment]
> so seems to be a morph issue, what are the diffs between demo-browser and morph ?

I first thought it had to do with scaling 
`qputenv("QT_AUTO_SCREEN_SCALE_FACTOR", "true");`
`QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling)`
but removing those lines in morph-browser.cpp did not make the list items show any better.
So currently I don't know why morph behaves differently here

**Comment by lduboeuf** [comment]
yes, i've tried also. But there is something that is related to HdpiScaling because if you choose PixMap* thing ( as in demo browser ) you get it working

**Comment by lduboeuf** [comment]
this issue afect edge and devel, can you update the label ?

**Comment by lduboeuf** [comment]
https://gitlab.com/mateosalta/qtwebbrowser_click/blob/exp/src/main.cpp#L60

( sorry, edit doesn't anymore on Morph, i think they break things, as our browser is not supported anymore )

**Comment by kugiigi** [comment]
It seems like it is indeed related to scaling?
Here's showing that it is displayed correctly on an external display.
I also tried setting the scaling on my Nexus 5 to 8 (same scaling on a 1080p monitor) and it worked correctly as well with that scaling.

![screenshot20191212_223707012](https://user-images.githubusercontent.com/29456786/70805317-eae0a400-1db8-11ea-9ea9-6318d476f6be.png)

**Comment by gbdomubpkm** [comment]
I can also say that on OPO dev, in order to have the subtitle option visible and select it (viewing the last Q and A on youtube), I had to scale  to 8.
But this is really not the normal scale for a good use of the phone !

**Comment by lduboeuf** [comment]
I've tried a workaround, by attaching a click event on `select` elements, pass options to a window.prompt so that we can handle it on QML side with `onJavascriptDialogRequested` ( i admit, it is a dirty hack :)) . This works ok for static DOM or within iframes, but for dynamic ones (e.g youtube filters ), we need to watch for DOM element creation (with MutationObserver), i'm afraid it is a costly thing in term of performance.

**Comment by zubozrout** [comment]
@lduboeuf I was thinking the same thing. Maybe it could be addressed from the C++ side of things but I have no idea how :/.

But yeah, as for observing all document changes and checking whether any select element appears in the DOM this seems quite costly.

**Comment by lduboeuf** [comment]
I think i've found something to get this working with js without having to listen to all new DOM elements. I need to test few things and if success, give a PR soon

**Comment by lduboeuf** [comment]
Can someone provides me some website that use select html elements ? ( i've tried only fews like on youtube, w3school )

**Comment by lduboeuf** [comment]
![screenshot20191218_003821460](https://user-images.githubusercontent.com/11663835/71131167-3bf6fa80-21f4-11ea-8e32-7e9392f6fbca.png)

Still not good with UI, but it works ( here on Youtube search filters )

**Comment by zubozrout** [comment]
> Can someone provides me some website that use select html elements ? ( i've tried only fews like on youtube, w3school )

This may be a bit of a challenge: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup :)

Anyway, awesome work, thank you @lduboeuf.

Btw, it seems there is currently no way to select multiple items in a multiselect option: https://www.w3schools.com/tags/att_select_multiple.asp but that is (I'd guess) for another ticket to be reported.

**Comment by lduboeuf** [comment]
Oh haven't heard of that optgroup thing, yes for another ticket i would suggest :)
Moreover  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup  has a special behavior, click on the select element is a custom event hold by a parent element. Will be hard to handle that for now since we need to look for childs select tags and make sure that the event concern the select element (here `target` element is the wrapper, not the select )....
[Edit] I see it is a "modern" way of reparenting events with Polymer or DOM shadow). I can do something about that

**Comment by Stefano0101** [comment]
This bug makes online banking virtually impossible on Edge channel. Since Ogra webapp won't work on arm64 build for Op3/t and normal webapp has the same issue.

**Comment by Stefano0101** [comment]
Maybe this helps? https://github.com/ubports/morph-browser/pull/273
wow! Great work! works magic! thanks for the fix.👍

**Comment by lduboeuf** [comment]
Glad it works :), now waiting for merge hopefully soon

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/morph-browser/pull/273

**Comment by zubozrout** [comment]
Hmm, I am not able to test this much but on current devel (Meizu MX4) it seems that on this page: https://www.tmb.cat/en/barcelona-fares-metro-bus/single-and-integrated/choose-ticket the select is completely empty. Any ideas what may that be? I wish I could test this on my pc and see what the select actually contains but have not one with me at the moment.

![screenshot20200220_191918331](https://user-images.githubusercontent.com/3088349/74965992-896f2e00-5416-11ea-9df9-224525fffbc1.png)

**Comment by lduboeuf** [comment]
i see option items are full of white space chars so it does not display well. I can't make the fix here but as soon as i'm at home i will do it ( next week), or if anyone can do that, we only need to trim whitespaces ( i guess )

**Comment by lduboeuf** [comment]
@zubozrout  can you please validate PR-302 for the empty list issue ?
`sudo ubports-qa install PR-302`

**Comment by zubozrout** [comment]
I only wish it was that easy on MX4 :), but I've installed these manually: https://repo.ubports.com/pool/PR-302/main/m/morph-browser/ and it looks great :). So, I can see the items in the select just fine now. Thank you @lduboeuf
