### ISSUE TITLE
Remote debugger not working in firefox.

### ISSUE THREAD

**Issue by extraymond** [ubports/morph-browser#246]
1. Device: nexus 5
2. OS: ubports edge channel 2019-10-19.

Hi! I got error when opening deubg tab in firefox while got a working one in chromium.

The error log:

```js
TypeError: document.registerElement is not a function
```

I'm suspecting this to be a polymer issue which can be fixed by inspecting its dependency.

**Comment by lduboeuf** [comment]
never thought it was possible to use Firefox for remote debugging, was it the case before ?

**Comment by lduboeuf** [comment]
I think it is more a chromium end to end thing

**Comment by extraymond** [comment]
Well that makes sense since they have similar core than firefox.
Just figuring if I can use my favorite browser to test it.

Is the front-end of the debugger implemented using polymer? I've seen bug reports about the same error log as above.

**Comment by lduboeuf** [comment]
> 

> Is the front-end of the debugger implemented using polymer? I've seen bug reports about the same error log as above.

Don't know sorry. But i doubt it is possible to use FF for debugging Chromium...

**Comment by extraymond** [comment]
I guess if the debugging is based on chrome-debug-protocol, then firefox can't be used.
Relative [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1316741) on firefox.

If that's the case, then I might be closing this since it's not a bug on morph itself.
