### ISSUE TITLE
Morph browser crash when clicking on Settings

### ISSUE THREAD

**Issue by lutin11** [ubports/morph-browser#249]
_Originally posted by @lutin11 in https://github.com/ubports/morph-browser/issues/233#issuecomment-546580768_

System: OTA-11 (20191016-9670)
Device: Nexus 5

This bug happen when clicking on settings from Morph Browser.
I reseted Morph setting using UT Tweak Tool without success.

This is the log that come after this action:

`propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.313\" (uid=32011 pid=5784 comm=\"morph-browser --desktop_file_hint=/usr/share/appli\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1978 comm=\"NetworkManager \")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.313\" (uid=32011 pid=5784 comm=\"morph-browser --desktop_file_hint=/usr/share/appli\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1978 comm=\"NetworkManager \")"
"Object path cannot be empty"
Received signal 11 SEGV_MAPERR 000000000004
#0 0x0000aafc9724 <unknown>
ubports/unity8#1 0x0000aa1ad74c <unknown>
ubports/unity8#2 0x0000aafc9aea <unknown>
ubports/unity8#3 0x0000b5b48270 <unknown>
[end of stack trace]
Calling _exit(1). Core file will not be generated.`

**Comment by lutin11** [comment]
I've just tried on development channel and I've got the same issue

**Comment by balcy** [comment]
so for my understanding changing the channels means you get the complete image DEV / RC / ... (you should then have exactly the same files in / as other users).
If that is identical and the clearing the settings does not help, I see nothing that would explain the problem on your phone.
