### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by lduboeuf** [ubports/morph-browser#253]
Ubuntu folder still accurate ? (marked as DEPRECATED)  https://github.com/ubports/morph-browser/tree/xenial/src/Ubuntu

**Comment by mateosalta** [comment]
I think for compatibility? so if you have packages that still import ubuntu.web it will actually load up morph stuff and not break

**Comment by lduboeuf** [comment]
ok i see, i close it for now as it is more a background task
