### ISSUE TITLE
Morph-browser crash when clicking on settings, on bookmark or addressfield

### ISSUE THREAD

**Issue by tux4us** [ubports/morph-browser#259]
```
Device: Sony Xperia X (5121)
Channel: dev
UbuntuTouch Version 41 (16.11.2019)
```
Morph-browser-app crash when clicking on:

- app-menue -> settings
- bookmark in the addressfield
- doubletap on the address in the addressfield

**Comment by lutin11** [comment]
Dear you, this bug as been reported there: https://github.com/ubports/morph-browser/issues/233

**Comment by tux4us** [comment]
> Dear you, this bug as been reported there: #233

With me so far occur 3 different errors in the Morphbrowser. That's why I opened a new bug report.
The errors I have described only occur on the Xperia x and Nexus5.
On the OneplusOne and the M10FHD, the Morphbrowser works without these errors.
All devices here are running on the channel: dev

**Comment by lutin11** [comment]
Have you tried changing the scaling ? it solve the problem for me ;)

**Comment by lutin11** [comment]
Have you tried changing the scaling ? it solve the problem for me ;)

**Comment by tux4us** [comment]
Thanks. It works.
