### ISSUE TITLE
There are no bookmarks on BQ M10 to use

### ISSUE THREAD

**Issue by tux4us** [ubports/morph-browser#266]
```
Device: BQ M10
Channel: dev
```
It is no longer possible to use bookmarks on the device BQ M10 in the channel dev.
Clicking on the star icon for bookmarks will bring up the confirmation menu, but the list for bookmarks will remain blank. The bookmark is created, however, because when the address is recalled, the star appears orange in color. However, earlier bookmark categories are available.

**Comment by balcy** [comment]
most likely caused by https://github.com/ubports/morph-browser/pull/244
(so this affects all devices)

**Comment by balcy** [comment]
if the homepage was set to an empty string (new tab page), the bookmarks view for all devices was not working (just showed a default icon without text for each bookmark)

if the homepage was set to a page, only the wide view (tablet / desktop) had problems.
Those should be corrected now with the mentioned PR
