### ISSUE TITLE
Hide title of private windows

### ISSUE THREAD

**Issue by mateosalta** [ubports/morph-browser#267]
Open a new private window - nagivate to website of choice 😅 - hold down on browser launcher to access quick launcher

what happens - title of page shown for the private window

exected - show generic "Private Window" label

**Comment by UniversalSuperBox** [comment]
I'm not sure I agree - Firefox on the desktop shows the title of the page you're browsing in private mode. Showing no label would be very confusing, especially if you had multiple private browsing windows open.

![image](https://user-images.githubusercontent.com/21966173/69894271-21abba00-12e3-11ea-9df6-58a6eaa8220b.png)

**Comment by mateosalta** [comment]
I think considering that mobile devices are more used in public, having these extra privacy focused considerations is important. I think should at least be an option to privacy screen. I usually only use one private tab as needed.

**Comment by mateosalta** [comment]
I have noticed that the quick-lists for the browser don't appear on the lock screen, that might be good enough.
