### ISSUE TITLE
Github unusable under ubuntu-touch

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/morph-browser#269]
Hello.
It is as much a question as it is a statement : it is now almost impossible to use Github under morph-browser, so with Ubuntu phones. It becomes a big blockage point. Do you know the reasons for this ? Is it due to updates in Github,  ¨lacks¨ in morph-browser... ?
Thank you.

**Comment by balcy** [comment]
unfortunately it is most likely due to an outdated chromium version, we currently try to find a way to build QtWebEngine 5.13 which updates chromium

**Comment by gbdomubpkm** [comment]
Thank you for the clear answer.

**Comment by balcy** [comment]
you're welcome ! More info is at https://github.com/ubports/morph-browser/issues/223

**Comment by Flaburgan** [comment]
Yep, this can be closed as a duplicate of #223 IMO.
