### ISSUE TITLE
Multiselect doesn't work on mobile - you can only select one item at a time

### ISSUE THREAD

**Issue by zubozrout** [ubports/morph-browser#272]
Hi,
I've just (https://github.com/ubports/morph-browser/issues/239#issuecomment-567370260) noticed that if one wants to select multiple options in a select there seems to be no way to do that (probably unless attaching a mouse and keyboard to the device). Long press only selects text in these items and allows you to copy it.

You can test the behaviour on this page for instance:
https://www.w3schools.com/tags/att_select_multiple.asp

Or is there any way around it?

**Comment by uratom962** [comment]
Hi ! I have the same problem on Ubports, can't copy past because I don't have the cursor, on an another software I found this bug too. Maybe it's the distro, I open a topic here with screenshot : https://forums.ubports.com/topic/3697/can-t-select-a-lot-of-letter-or-a-word/3

**Comment by zubozrout** [comment]
@uratom962 I am afraid this is a completely different issue report than what you are describing. This report is (as per links in the description), about selecting options in a dropdown field on websites, nothing about copy/paste. If you feel like that issue needs reporting and can't find it reported already somewhere, please open up a new issue for that. Thank you.

**Comment by lduboeuf** [comment]
i've tested on N5 the multi select and seems to work for me.

**Comment by zubozrout** [comment]
Hi @lduboeuf, thank you for trying this. This report has been made prior your awesome pulldown menus were merged so it is a bit out of date apparently.

However, what I am now experiencing on my MX4 devel is a bit weird behaviour:

1. A multiselect DOM element lists all options right on the page, just as on desktop:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple. Apparently Android shows this just as a regular select and then give user the option to select none, one or more items in a popup - there is a screenshot of the pop-up here (the web page rendering is different to the Chrome emulation on desktop): https://stackoverflow.com/questions/55500356/feature-detect-advanced-browser-multi-select-control-e-g-ios-android-select
2. I can click on one of the items in the list but when clicking on a different item, the other gets selected and I am not sure how to select another one while keeping the previous selections. Although with some wild tapping I am (at random) able to select more than 1 item (not just selecting the word for copy/paste, but really selecting more than 1 item in the list). Anyway, I am not able to reproduce and don't know how to deliberately select more than one item in the list using this procedure.
3. If I hit the outer border of the multiselect listing then the select pop-up will appear. That seems to allow selecting an additional item (keeping previous selections active).

So I suspect this issue can be closed (and I am closing it as no longer valid), though it would be nice if it could be a bit more intuitive.
