### ISSUE TITLE
Webapps do not open links from url dispatcher

### ISSUE THREAD

**Issue by giiba** [ubports/morph-browser#295]
Currently, when a webapp is made with a url-dispatcher file, the links are redirected to the app but the default page is loaded.

Expected behaviour:
the passed link should be opened, not the default page

As I cannot guarantee this is Morphs fault see this web app I made in case there is something I have configured wrong:
https://github.com/giiba/Github_UT

**Comment by mateosalta** [comment]
does it work if you use the link twice, second one onec the webapp open?

**Comment by giiba** [comment]
No, still doesn't work. If the app is not open it is opened to the home page, if the app is open focus is switched and nothing happens (ie whatever page it was on is still displayed).

**Comment by balcy** [comment]
ok so with the change in https://github.com/ubports/morph-browser/pull/308 (https://github.com/ubports/morph-browser/pull/308/commits/fd92f234350636edce91f297afeff59718b0197a) I was able to make the URL loading possible (if the app is already running), but I additionally changed the following in the github.desktop file:
`--webappUrlPatterns=https?://github*.com/*` => `--webappUrlPatterns=https?://github.com/*`

If the webapp is not already running, I think it has to be provided via command line, so I've added the `%u` to the command in the github.desktop file:
So the command line is:
`Exec=webapp-container --store-session-cookies --enable-back-forward --webappUrlPatterns=https?://github.com/* https://github.com/ubports %u`
