### ISSUE TITLE
Ebay website horizontal scrolling isn't possible

### ISSUE THREAD

**Issue by ghost** [ubports/morph-browser#297]
Scrolling through pictures isn't possible.
Also scrolling through offers on the startsite doesn't work.
It does work using the webapps from the store.

Devices / Channels:
Oneplus 3T / edge
Oneplus One / rc
BQ E5 / rc

**Comment by ghost** [comment]
Doesn't work on the Oneplus 3T:
![screenshot20200216_161959398](https://user-images.githubusercontent.com/46136222/74607569-39bcf980-50da-11ea-851f-ec3310c97ab5.png)
![screenshot20200216_162231784](https://user-images.githubusercontent.com/46136222/74607572-45a8bb80-50da-11ea-869a-6bca04b52e94.png)

Does work using Fennec/LineageOS:
![247538285_195424](https://user-images.githubusercontent.com/46136222/74607591-725cd300-50da-11ea-90be-b48c6171d356.jpg)

**Comment by gbdomubpkm** [comment]
@thilovv Seen with Ebay website  : For me, this is not always obvious, but right and left scroll arrows tend to appear more easily when the phone is in landscape mode (bq E5 HD and OPO). If they appear, scrolling is possible.

**Comment by ghost** [comment]
Thanks!
I have seen the scroll arrows just in special offers sites. But scrolling through pictures and the "standard offers" on the startsite is never (even in landscape mode) possible since month now.

**Comment by gbdomubpkm** [comment]
@thilovv  qt update (dev channel currently) solved the problem i think
