### ISSUE TITLE
Morph Browser crash/termination after expanding dropdown box

### ISSUE THREAD

**Issue by VolkerBartheld** [ubports/morph-browser#300]
This probably relates to issues #54 and #239. I'm using Morph Browser on my Asus/Google Nexus 7 2013 WiFi as part of the Ubuntu Touch 16.04/stable (OTA-11), all updates installed.

Whenever I try to expand a dropdown box such as "Font Size" in https://en.m.wikipedia.org/w/index.php?title=Special:MobileOptions, the Morph Browser app terminates. I briefly see the splash screen after tapping the dropdown box, however no browser instance comes up and the original instance has disappeared. Happens with other dropdown boxes as well, e. g. changing the font/font size in https://imaginarysense.github.io/Teleprompter-Core/.

**Comment by lduboeuf** [comment]
might be related yes, next OTA update will hopefully fix it ( i don't have that issue on devel now )

**Comment by lduboeuf** [comment]
we should close this now @UniversalSuperBox since it is fixed on RC/devel

**Comment by UniversalSuperBox** [comment]
This issue was fixed by https://github.com/ubports/morph-browser/pull/273, which is currently being tested in `devel` and `rc`. We prefer to have tickets which only relate to issues in `devel`, so I will close this report.

**Comment by VolkerBartheld** [comment]
@UniversalSuperBox&lduboeuf: Thanks for the update. I have switched to the rc-branch on my device and updated Ubuntu Touch. I can confirm that the issue with expanding the dropdown box crashes Morph browser is fixed.
