### ISSUE TITLE
"canGoBack" change does not propagate when changing the url (e.g. via address bar)

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#306]
- open morph with the homepage (e.g. start.duckduckgo.com)
- write another url (e.g. ubports.com) in the address bar

expected result: the back button is enabled
actual result: the back button is not enabled

I don't know why the change of the flag is not properly propagated:
In fact if you manually evaluate webview.canGoBack after navigating to the page, it is "true", but the property is not automatically updated.

**Comment by lduboeuf** [comment]
confirmed

**Comment by balcy** [comment]
with branch https://github.com/ubports/morph-browser/tree/xenial_-_cangobacksignal you can see the problem on the phone or with `clickable desktop`:
- set the browser to start with a homepage (e.g. start.duckduckgo.com) or you can use "restore session" on the phone as well.
I've added two items to the menu, one shows "currentWebview.canGoBack" in its own text, and if you click on it as message.
The other one changes the url of the webview to "https://ubuntu-touch.io".

![image](https://user-images.githubusercontent.com/848115/77230564-5fd03080-6b95-11ea-8967-3f1313fe225b.png)

if you click the first item in the menu, you see
![image](https://user-images.githubusercontent.com/848115/77230577-7c6c6880-6b95-11ea-8789-f2626d7d4bf4.png)

then click the second item in the menu (link to ubuntu-touch.io) and after the page has loaded, open the menu again.
![image](https://user-images.githubusercontent.com/848115/77230642-ec7aee80-6b95-11ea-820d-9fd04bb39cef.png)
the back button is still not enabled, and the text in the menu not updated.

but if you click on the first item, you see that in fact "canGoBack" has changed to "true" by now:
![image](https://user-images.githubusercontent.com/848115/77230674-2d730300-6b96-11ea-95c4-2c57ff02144c.png)

this change should have "reported" to the elements with that binding some time before the loading of the new page is finished, but somehow the event does not arrive.

The browser itself can go back without problems (e.g. when you make the back button always enabled, the browser can go back to the original page). So it's just the question why the event is lost.

It is not lost when just navigating via links (e.g. clicking on the duckduckgo picture instead of changing the url of the webview)

A workaround is to trigger a "urlChanged" event after the loading has finished.
