### ISSUE TITLE
Unable to sign in at gitlab

### ISSUE THREAD

**Issue by ghost** [ubports/morph-browser#313]
Since some time I can't sign in at gitlab. I tried Username/Password and "sign in with github".

Devices: Oneplus 3t and BQ M10

All I get is this page:
![screenshot20200410_121536045](https://user-images.githubusercontent.com/46136222/79131702-50fe2780-7da9-11ea-9b32-94e96c1a3241.png)

**Comment by lduboeuf** [comment]
confirmed for me too N5 devel

**Comment by cibersheep** [comment]
^__^ Oh, it's open already. Well, I can confirm that with Arale Dev channel and N5 RC (2fa activated in my account)

**Comment by lduboeuf** [comment]
isn't it an issue in gitlab itself ?

**Comment by cibersheep** [comment]
I just logged in from Firefox on desktop...

**Comment by gbdomubpkm** [comment]
Seen with BQ E5 HD.
Seems impossible to log in to Gitlab now with the Gitlab username and password !  Probably since the last update of their site ?

Hi @balcy Have you an idea what's happening ? Do you think qt update will solve that ? Thank you.

**Comment by ruedigerkupper** [comment]
Confirmed on Xperia X (suzu). Could that be the same problem keeping us from signing in to Google? Websites classify Morph as outdated / possibly dangerous?
Even Git Hub complains „this browser is no longer supported“, but still allows login.

**Comment by ruedigerkupper** [comment]
Reference:
https://github.com/ubports/ubuntu-touch/issues/1456

**Comment by gbdomubpkm** [comment]
qt updare (dev channel currently) solved the problem for the log in on  Gitlab on UT smartphone
