### ISSUE TITLE
Unable to sign in at ebay-kleinanzeigen.de

### ISSUE THREAD

**Issue by ghost** [ubports/morph-browser#314]
Since some time I can't sign in at ebay-kleinanzeigen.de

Devices: Oneplus 3t and BQ M10

All I get is a white page.

**Comment by minibootsmann** [comment]
This still Lappens. I use a BQ M10HD anderen I get a blank page when trying to login at https://kleinanzeigen.ebay.de.

**Comment by balcy** [comment]
on dev (BQ Aquaris 4.5) I can login.

**Comment by ghost** [comment]
Yes, on dev it works now. @minibootsmann if you are not using the dev channel I will close this issue.

**Comment by minibootsmann** [comment]
No, I don't use the dev channel as I am new to ubports and still working hard on setting all things up to get a usable device.
Thank You for this hint, I will search for information about the dev channel.
