### ISSUE TITLE
Site keep asking for location permission

### ISSUE THREAD

**Issue by dark-eye** [ubports/morph-browser#320]
there seems to be no way to permanently deny location permission to a given site.
ask mark 'remember choice' disables the Deny button.

for example tyr the following stie it will ask for location permission for every page:

[https://www.zap.co.il](https://www.zap.co.il) (Hebrew site, be ready for RTL orientation :))

Device: BQ Aqurias m10
SDK:16.04

**Comment by balcy** [comment]
I think we can make it remember the decision "never allow location": https://github.com/ubports/morph-browser/tree/xenial_-_locationsettings
