### ISSUE TITLE
It's too hard to close the current tab

### ISSUE THREAD

**Issue by doniks** [ubports/morph-browser#325]
Reproduction:
* open five tabs and surf somewhere
* try to close the current tab

Observed:
It is quite cumbersome. I have to
* swipe up to the get the tab list 
* select another tab 
* swipe up again
* find the original tab in the list
* hit the x 

Expected:
I would expect that with two gestures and without any searching on the screen I should be able to close the current tab

**Comment by UniversalSuperBox** [comment]
Hi @doniks,

It is possible to close the current browser tab by pressing the "X" icon that appears when the tab view is open.

![image](https://user-images.githubusercontent.com/21966173/84603567-f179d200-ae54-11ea-9005-c16cb3ed1890.png)

Is this what you are looking for?

**Comment by doniks** [comment]
ohhh. You are right. I never noticed. Now I wonder, is it just me, or is this x just not discoverable ....

**Comment by doniks** [comment]
i find one earlier instance https://github.com/ubports/morph-browser/issues/196

**Comment by kugiigi** [comment]
This was implemented during the QtWebEngine transition. The current tab is included in the tab list before but now the navigation bar persists and the close button was added. I'm not sure the technical reasons for this though. But definitely, it was more consistent and better discovery before.

**Comment by Rebecca-du-58** [comment]
I don't have the cross on Morph.

**Comment by doniks** [comment]
> I don't have the cross on Morph.

screenshot?
