### ISSUE TITLE
Open Link in a Backgroun Tab Puts It As the Last in the Queu

### ISSUE THREAD

**Issue by cibersheep** [ubports/morph-browser#326]
On Phones:
- Open several tabs
- In a website tap and hold on a link
- Select «Open link in a background tab» 

Current behaviour:
- tab goes into the last tab. To see it afterwards, you need to open tab spread and scroll down until the end

Expected:
- Tab opens next to the current tab (no focus)

**Comment by matzgewinn** [comment]
xperia x compact, 2021-W27,  works.
