### ISSUE TITLE
Deleting a download does not delete the file

### ISSUE THREAD

**Issue by kugiigi** [ubports/morph-browser#330]
## Steps to Reproduce
1. Download a file
2. Wait until it completes (Getting an error is also fine)
3. Delete the completed/failed download

## Expected Results
The download is delete from the list and the corresponding file is deleted

## Actual Results
The download is delete from the list and but the corresponding file is retained.

## Additional information
I'm not sure if this is intended but if it is, perhaps an option to delete both is an option.
I'm also actually checking the code right now so I can do a fix myself :)

**Comment by onlygecko** [comment]
I can't confirm this bug on the PinePhone (rc channel: OTA-5). 

But what I've noticed is: 

1. Download a pdf file.
2. Open it with the file manager.
3. Switch back to the download list.
4. Delete the download.
5. Switch back to the file manger.
6. _then the pdf file entry is still shown. After refreshing the directory the file is not visible any more._

It seems, the file manager does not update the contents of the current directory when the user is switching back to the file manager.

@kugiigi: Can You confirm this? 

Greetings,
Peter

**Comment by kugiigi** [comment]
Are you sure? I just tested on my pinephone on latest devel image and I can confirm that the file is not deleted when deleting from Morph. I kinda confirmed this in the code as well and in fact I'm preparing a PR right now which will include a fix for this 😄

**Comment by onlygecko** [comment]
Maybe something broke between OTA-5 and DEV? I've tested it with different sites in private and normal browser mode. :-/

**Comment by cibersheep** [comment]
This is the expected behaviour.
If you clean the list of downloads, you expect the files to stay

**Comment by kugiigi** [comment]
> This is the expected behaviour.
> If you clean the list of downloads, you expect the files to stay

I see. That's what I thought because it seems to be changed intentionally. However, when deleting multiple downloads at a time, the files are actually deleted so I got the idea it's a regression. Anyway, I implemented a separate action `Remove` in #336.

**Comment by cibersheep** [comment]
Oh, I didn't know that. 
Files should be removed in the File Manager not in the Browser

**Comment by lgtrombetta** [comment]
Works as expected on the Nexus 6P - RC 2021-W08

**Comment by dadandalive** [comment]
I confirm that on Nexus 5 (RC 2021-W10) a deletion from the Downloads list, removes both the reference in the Downloads list as well as the file itself.

I'm however on the same page as @cibersheep, believing that this behaviour is not in line with that of other browsers. And this might confuse users. Additionally, I would like to point out that synchronization is neither assured in the other direction: if a file gets deleted from the Downloads folder, the reference in the Downloads list still remains (as I believe it should, even if some UI indication of file deletion would be welcome). 

So, in my opinion it would have been better to instead modify the multi-select deletion (preventing it from actually deleting the files). And if current file deletion behaviour is maintained, a user warning of the file deletion might be needed.
