### ISSUE TITLE
App ID when using clickable is wrong

### ISSUE THREAD

**Issue by kugiigi** [ubports/morph-browser#335]
## Description
I discovered that the appid when using clickable is the one below. I guess it was patterned to the clock app? 😄 
`com.ubports.morph.browser_clock_0.1`

**Comment by balcy** [comment]
The clock comes from
https://github.com/ubports/morph-browser/blob/65859e538d52281cc04c5a6554c403038b0f2389/src/app/webbrowser/manifest.json.in#L9
