### ISSUE TITLE
QML layouting issue in webapp-container ?

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/morph-browser#338]
Some webapps created with the webber app may not display the options strip of the website at the bottom of the screen. This is very annoying for the use of these webapps.
This has been observed for a webapp created from https://m.lequipe.fr/Tennis/ when   **--enable-addressbar flag is set.**
But for my bank site, which uses an option strip, even when --enable-addressbar flag is NOT set, this option strip is not visible: impossible to use the bank webapp!
see full discussion here https://github.com/timsueberkrueb/webber/issues/27

**Comment by balcy** [comment]
for the problem with the address bar https://github.com/ubports/morph-browser/blob/0c31c8f7ee35b169bffffa60800b53b4bee988d4/src/app/webcontainer/WebApp.qml#L217 ([EDIT] https://github.com/ubports/morph-browser/pull/351) should fix it.
For the bank site I don't know, does it display the bottom in morph ?

**Comment by gbdomubpkm** [comment]
Thank you for your answer.
Under morph-browser, with the bank site, i have no problem : i see the options strip and i can use options. I'm waiting your fix in dev to see what's happen for the webapps.

**Comment by gbdomubpkm** [comment]
Seen on BQ E5 HD : confirmed, the options strip is there even for the  bank webapp ! A very useful fix for daily use webapps !
Thank you @balcy and @UniversalSuperBox
