### ISSUE TITLE
Morph Browser - untranslated - German

### ISSUE THREAD

**Issue by openlewa** [ubports/morph-browser#339]
Please Fix. Thank you in advance.
![20200617_202113](https://user-images.githubusercontent.com/54738746/85175126-1b792d00-b277-11ea-9992-890f2f572894.jpg)
Clear all Cookies? = Alle Cookies löschen?

![20200617_202006](https://user-images.githubusercontent.com/54738746/85175121-187e3c80-b277-11ea-8c8b-14aa40c980c6.jpg)
Clear cache? = Cache leeren?

![20200617_201903](https://user-images.githubusercontent.com/54738746/85175113-14eab580-b277-11ea-82e8-0b44bcd545e2.jpg)
Clear browsing history? = Browserverlauf löschen? 

![20200617_201644](https://user-images.githubusercontent.com/54738746/85175108-11572e80-b277-11ea-8552-5f87cb234aa4.jpg)
Start in private mode = starte im privaten Modus
Domain specific settings = Domain spezifische Einstellungen
Clear browsing history = Browserverlauf löschen
Clear cache = Cache leeren
Clear all Cookies = Alle Cookies löschen

![20200617_200136](https://user-images.githubusercontent.com/54738746/85175095-0b614d80-b277-11ea-873b-a0e47220c57a.jpg)
New Tab Page = Neuer Tab Seite
Automatic fit to width = Breite automatisch anpassen
Adjust the width of the website to the window = Passt die Breite der Seite an das Fenster an

![20200617_200949](https://user-images.githubusercontent.com/54738746/85175103-0e5c3e00-b277-11ea-89de-9072f4b1d67c.jpg)
New Tab Page = Neuer Tab Seite
Custom hompage = Custom homepage = Benutzerdefinierte Startseite

**Comment by Flohack74** [comment]
Can someone please check if those strings are properly localized in the code?

**Comment by balcy** [comment]
It looks ok in the code, at least the "Clear Cache" / "Clear Cache?" are with i18n.tr(...) in the qml files and the pot file.
There were some line changes in the SettingPage (and others) in the morph-browser.pot file that are not reflected in the de.po file.
The last change of the .pot file was 6 months ago, but de.po (100% translated in weblate) was changed 8 months ago:
https://github.com/ubports/morph-browser/tree/xenial/po
Does weblate pull the .pot file from the xenial branch ? Is it done automatically ?

**Comment by Flohack74** [comment]
Weblate is broken sometimes, but first I wanted to know if pot has been requenerated. If you say so, I can look further thanks ^^

**Comment by balcy** [comment]
ok alright, but it was a good heads-up anyway, because the current pot file is from last december and should probably updated again anyway. (but at least the examples shown above should be in the current pot file from last december)

**Comment by balcy** [comment]
I think flohack updated the translations.
