### ISSUE TITLE
Systematic crashes of morph-browser or webapp (webber)

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/morph-browser#341]
@balcy @UniversalSuperBox  seen today with the last update in dev  (OPO, BQ E5 HD..)
 
Steps to reproduce :

take this site for example : https://www.deepl.com
- Position the cursor in the posting field ;
- Write or not write a few characters in the translation area and **keep the keyboard visible**;
- Move the screen up and down: at some point, morph-browser or the webapp crashes !

I hadn't seen this so systematically in a long time...

By performing the same manipulations on all web pages, all webapps where there is a writing area and **keeping the keyboard visible**, morph-browser or a webapp crashes at some point and usually very quickly.

**Comment by balcy** [comment]
Could this be a problem related to the upgrade of QtWebEngine and old cache still present ?
Does it still crash after you do "Clear Cache" from the settings?
There are reports with crashes on Qt upgrades for qutebrowser, too: https://github.com/qutebrowser/qutebrowser/issues/4853
I've seen more crashes myself when switching from Qt 5.13 to 5.14 or 5.11 to 5.14
We might need to ask the user or automatically clean the cache the first time a user uses morph or a webapp with new Qt.

But all of this this would not explain how the keyboard is involved in the problem.
At least I cannot reproduce the crash on my BQ 4.5 right now.

**Comment by balcy** [comment]
there are even crashes that go away after 72 hours (Qt5.12 but could apply for 5.14) https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-72532

**Comment by gbdomubpkm** [comment]
More precisely try with deepl (web or webapp) with the steps and by sliding your finger on screen upwards.
Clean cache change nothing for me.

**Comment by balcy** [comment]
ok, do you have to be logged in on the deepl page?

**Comment by gbdomubpkm** [comment]
No, free use.
And it did the same thing now on my github webapp with the  OSK visible. If the OSK not visible, no problem for me.

**Comment by gbdomubpkm** [comment]
.... and i confirm that you are right for the bq 4.5 : i don't see  the problem !!! (dev 554).
But yes on OPO, BQ E5 HD for me !

**Comment by balcy** [comment]
ah ok, that's the only device I have...
(and Raspberry Pi 3)
otherwise I could have tried if I see sth. with GDB

**Comment by gbdomubpkm** [comment]
Incredible that given the great services you provide to the community as a super developer, you only have the BQ 4.5, very good basic phone indeed !

**Comment by balcy** [comment]
yeah even have used it with dual sim for some years, hopefully it will keep running a few more months : )
Maybe @UniversalSuperBox  can debug it (if he sees the bug), it would be interesting to know if it only appears in morph / webapp-container or in other QtWebEngine based browsers, too.
E.g. if you clone `https://gitlab.com/balcy/qt-webengine-demo/` and build it with clickable.

**Comment by lduboeuf** [comment]
got it today on N5  on Youtube webapps. Got a crash every time. Need to see if anything wrong with cache. But returnes to RC since...

**Comment by balcy** [comment]
@lduboeuf Do you see the crash on scrolling, or did it not load at all ? It might just be the missing env. variable then. (If the youtube webapp does use QtWebEngine directly)

**Comment by gbdomubpkm** [comment]
Me too, back to RC on my main phone BQ E5 HD as long as the problem is there : I lose one of the advantages of qt 5.14 (sign in/up again possible on GITLAB with UT smartphone) but there are no more crashes !!

**Comment by balcy** [comment]
I wanted to write how I usually debug QtWebEngine via morph:
- update packages in libertine container `apt update`
- install gdb and libqt5webenginecore5 in the xenial libertine container `apt install gdb libqt5webenginecore5`
- install `https://ci.ubports.com/job/ubports/job/qtwebengine-opensource-src-packaging/job/xenial/2/artifact/libqt5webenginecore5-dbgsym_5.14.2+dfsg-1ubports0_armhf.ddeb` in the libertine container via dpkg
- in /home/phablet (outside of libertine) place a file `setEnv.sh` with the following content:
```
#!/bin/bash
export PATH="$PATH:/home/phablet/.cache/libertine-container/xenial/rootfs/usr/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/phablet/.cache/libertine-container/xenial/rootfs/usr/lib/arm-linux-gnueabihf"
```
- in a ssh shell (or with `ssh ::1` from the terminal app), run the command `. setEnv.sh`
- morph-browser must not be running on the phone
- run the command `gdb --args morph-browser --desktop_file_hint=/usr/share/applications/morph-browser.desktop` or `gdb --args morph-browser --desktop_file_hint=unity8`
- You see the following:
```
Reading symbols from morph-browser...(no debugging symbols found)...done.
(gdb)
```
- Type `run` and press enter
- it should take quite some time to load the debugging symbols of QtWebEngine (which is a good sign)
- You see the following:
```
Program received signal SIGILL, Illegal instruction.
0xad53bf48 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
(gdb)
```
- Type `continue` and press enter
- Then morph should open
- When the crash occurs hopefully some information about a segfault / other error will be found

**Comment by lduboeuf** [comment]
> @lduboeuf Do you see the crash on scrolling, or did it not load at all ? It might just be the missing env. variable then. (If the youtube webapp does use QtWebEngine directly)

Crash at app load,  i used that one: https://github.com/mateosalta/cuddly-bassoon

**Comment by gbdomubpkm** [comment]
Just for info, Nexus 5 is not spared by the crash when scrolling in dev (OSK apparent).
Example:
- Gitlab website;
- Sign in;
- Scrolling up with OSK: direct crash !
Only the BQ 4.5 seems to be spared for the moment 😁

**Comment by balcy** [comment]
good (or bad) news for BQ Aquaris 4.5 :
When changing the scale in UT Tweak tool to 10 (original value is 12) I see the crash, too.
`Thread 29 "QSGRenderThread" received signal SIGSEGV, Segmentation fault.`
We might try how the version without the auto screen scale factor behaves.

**Comment by balcy** [comment]
this reproducable crash does not happen for me (even with that scale) with `QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu" morph-browser --desktop_file_hint=unity8` 
only if `--disable-viz-display-compositor` is used. Then it is similar to the QtWebEngine 5.13 behavior.
https://github.com/ubports/qtwebengine-opensource-src-packaging/issues/35

**Comment by gbdomubpkm** [comment]
Empirically tested (many restarts), i can say that i did not see any crashes for these scaling :
- BQ 4.5        11 ; 12
- OPO           15 ; 16 ; 17
- NEXUS 5    16  ; 17
- BQ E5 HD   Not done !

**Comment by cibersheep** [comment]
Ouh, I happen to test Dev from yesterday on E5

http://paste.ubuntu.com/p/vRKzFdqgKb/

This crash happened on webviews in qml files (Flas, uNav, etc) but not in html5 apps (Inoreader, Turtl, etc)

Do I need to test recent changes though

**Comment by balcy** [comment]
without the high DPI auto scale (branch https://github.com/ubports/morph-browser/tree/xenial_-_nohighdpiautoscale), the crash does not happen to me. So I suspect the crash happens in qtbase and is related to high DPI scaling.

**Comment by cibersheep** [comment]
On E5 20200720 fixed the issue. 
Is there something you want me to test?

**Comment by gbdomubpkm** [comment]
Back to dev on BQ E5 HD ! 
So no scrolling crash too only for scaling 16 and 17

**Comment by MK1973** [comment]
I can confirm crashing also on FP2, N5, osk on and trying to scroll the window, perhaps.

**Comment by ruedigerkupper** [comment]
Confirming crashes on Xperia X (suzu).

**Comment by lduboeuf** [comment]
on BQ4.5, after several apps opened, did a search on github, tried to sort the result, qml select popup is displayed and don't remember if i got a unity8 restart by selecting one item or just before

**Comment by gbdomubpkm** [comment]
Tested BQ E5 HD : Fixed, not seen any new  scrolling crashes. 👍

**Comment by laborim** [comment]
Device: oneplus 3
Channel: rc
Build: 2020-W35/2

Seems fine. I can't reproduce the error

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W35/2

Can't reproduce the issue.

**Comment by AppsLee** [comment]
Device: Nexus5
Image: 2020-W35/2

Cannot reproduce. Seems fixed to me.

**Comment by peat-psuwit** [comment]
Three confirmation. Considering solved.
