### ISSUE TITLE
Closing one browser window closes all

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#35]
steps to reproduce:
- From the menu top right select "new window" or "new private window", choose your start page or any other bookmarked page.
- Close one of the windows
Result: All browser windows are closed
Expected: The other browser windows remain open

**Comment by balcy** [comment]
... just seen that this happens for the webbrowser-app as well

**Comment by balcy** [comment]
issue opened for the webbrowser-app :
https://github.com/ubports/ubuntu-touch/issues/574

**Comment by Ingo-FP-Angel** [comment]
Device: FP2
Channel: RC
Version: 2018-W01

I cannot reproduce the bug, i.e. the fix works.

**Comment by 10JML01** [comment]
Device: BQ E5HD and M10FHD
Channel: rc
Version: 2018-W01

Fix works. Cannot reproduce the bug.

**Comment by advocatux** [comment]
Device: Nexus 5 (hammerhead)
Channel: RC
Version: `2018-W01` (_really_ `2019-W01`)

Fix works. I can't reproduce this issue.
