### ISSUE TITLE
OPO: crash on saving favorite web pages (scaling 20)

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/morph-browser#358]
OPO dev 1531

Strange: for me, morph-browser crashes on saving favorite web pages with a scaling of 20!  Not 19, not 21...  Only 20 found.  Despite the crash, the web page is recorded as a favorite.  If I uncheck the star, no crash.  Checking it again crashes.
Not tested on other devices.

**Comment by gbdomubpkm** [comment]
Idem BQ E5 HD scalling 20 also..

**Comment by balcy** [comment]
confirmed on BQ Aq. 4.5 with scale of .... 20

**Comment by balcy** [comment]
https://github.com/ubports/morph-browser/issues/311

**Comment by gbdomubpkm** [comment]
Indeed !! And moreover I had already tested, commented, and... forgot about this bug !!
