### ISSUE TITLE
Video too big / too small in fullscreen mode, when zoomFactor != 1.0

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#360]
- go to a page that has a video in landscape format that can be put to full screen
- device is in landscape orientation

1)
- set the zoom to 50% 
- set video to full screen
expected result: the video covers the whole screen
actual result: video is smaller (covers only part of the screen)

2)
- set the zoom to 150% 
- set video to full screen
expected result: the video covers the whole screen
actual result: video is bigger (only part of the video is displayed on the screen)

**Comment by Rebecca-du-58** [comment]
I have the same problem. the image is cropped unless I be in landscape mode.
