### ISSUE TITLE
Html5 apps can't access LocalStorage anymore

### ISSUE THREAD

**Issue by cibersheep** [ubports/morph-browser#367]
Apps like https://github.com/esviji/esviji-ubuntu-touch can't access localStorage anymore (on dev channel)

- Esviji can remember game position after restarts
- Morph doesn't create `.local/share/[app]/Local Storage` folder
- LocalStorage is accessible while app is open but not persistent

**Comment by balcy** [comment]
QtWebEngine changed the default of 'offTheRecord' of the WebEngineProfile to false:
https://github.com/ubports/morph-browser/issues/347
Therefore the profile is only in memory, if not explicitely set to permanent.
As discussed in the other thread, it is a breaking change for Morph.Web, but follows QtWebEngine here.

**Comment by balcy** [comment]
not tested, but https://github.com/esviji/esviji-ubuntu-touch/pull/7/files should fix it.

**Comment by cibersheep** [comment]
THANk YOU A TONE
as I would not have found that like... never.

I think going upstream is good. Just happy to know how to go our way :)

I send some distance love

**Comment by balcy** [comment]
thanks! Maybe we can identify the most important apps and send them hints / PR's too. Unfortunately some apps in open store have dead source links or no source linked at all.
The good thing is the change can be done in stable already, and then the app will work both now and after OTA-13

**Comment by cibersheep** [comment]
Maybe a cool announcement on Saturday? Is Q&A day

**Comment by cibersheep** [comment]
Tested on a couple of apps. Your fix is working. Thanks!
I should close this
