### ISSUE TITLE
Morph browser incorrectly identifies itself as OS Andoid 4.4

### ISSUE THREAD

**Issue by dtarrant2019** [ubports/morph-browser#374]
WhatsMyBrowser.org reports UT as OS Android 4.4 unless 'Set desktop mode' is selected in browser settings. This causes the BBC website to complain about an out-of-date browser and block register/sign-in.
I have experienced this problem with Nexus 4 and PinePhone devices running latest RC.
Selecting 'Set desktop mode' results in WhatsMyBrowser.org reporting OS Ubuntu 16.04 and the BBC website register/sign-in process working correctly.

**Comment by dtarrant2019** [comment]
This subject is discussed on the UBports forum at:
https://forums.ubports.com/topic/4833/pinephone-browser-not-working-with-some-websites

**Comment by balcy** [comment]
thanks for the report, can you post the link to the page for which registering is not allowed ?
Is it https://account.bbc.com ? For that I cannot see the error message yet.
In any case, we should probably change the 4.4 to 9 here.

**Comment by dtarrant2019** [comment]
Hi Chris,

If I click on my user icon, the url to my account details begins as follows:

https://account.bbc.com/account?<https://account.bbc.com/account?ptrt=https%3A%2F%2Fwww.bbc.co.uk%2Fnews&context=news&userOrigin=news_ps>**************

Not sure if the above is relevant. Once logged in, the BBC website keeps you logged in between sessions unless you choose to log out.

I previously solved my login problem by switching Morph to desktop mode and was able to log in and have not logged out since.

I agree we should change 4.4 to 9.

Regards,

David

________________________________

**Comment by dtarrant2019** [comment]
Tested Nexus 4 today and whatsmybrowser.org now correctly reports OS as Ubuntu 16.04.
Also fixed for Pinephone.
Thank you UBports

**Comment by lgtrombetta** [comment]
> Tested Nexus 4 today and whatsmybrowser.org now correctly reports OS as Ubuntu 16.04.
> Also fixed for Pinephone.
> Thank you UBports

It works correctly also on the Nexus 6P - RC 2021-W08

**Comment by dadandalive** [comment]
Works on Nexus 5 - RC 2021-W10.
