### ISSUE TITLE
blocked / allowed domains settings page should be sorted chronologically (descending) by default

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#383]
sometimes you have blocked a domain and later would like to allow it.

example:
- go to "Settings" -> "Privacy & Permissions" and make sure "Only allow browsing to whitelisted websites" is checked
- navigate to https://ubports.com/blog/ubport-blogs-news-1/post/ubuntu-touch-q-a-84-3719 (allow the domain ubports.com if asked)
- click on the button "Get the Audio Version"
- click "Block domain" for the domain soundcloud.com
- click the button "Get the Audio Version"
- a message "blocked navigation request to domain soundcloud.com" appears
- to fix this, you can go to "Settings" -> "Privacy & Permissions" -> "Domain blacklist/whitelist"
- per default it is sorted alphabetically, so it is not easy to get to the soundcloud.com domain
- if you click on the "Az" symbol (alphabetically sorted), it turns into a clock symbol and you see soundcloud.com right at the top
- you can either set it to "Always allow access" or "Not Set"

I'd suggest to display the list that way by default, so you see what happened recently, and don't have to click the sorting symbol in the header

**Comment by jonnius** [comment]
I confirm the list is sorted by date instead of alphabetically by default (Xperia X RC).
