### ISSUE TITLE
Enable copying content to the Clipboard via JavaScript

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#389]
It is not always possible to copy text to the clipboard via Javascript.

- open https://github.com/ubports/morph-browser/blob/xenial/morph-browser.png in morph
- click the dots right (not the ones in the header bar, but the one for the file)
- click copy path
- paste the path e.g. in the terminal app, or the address bar
![image](https://user-images.githubusercontent.com/848115/94342597-575c2500-0012-11eb-9d69-d6fa06456648.png) 

- expected result: the string `morph-browser.png` is pasted
- actual result: the previous content of the clipboard (or nothing) is pasted 

setting https://doc.qt.io/qt-5/qml-qtwebengine-webenginesettings.html#javascriptCanAccessClipboard-prop to true solves the issue

**Comment by balcy** [comment]
the log file entry (without the setting) is `qml: [JS] (https://github.com/ubports/morph-browser/blob/e66f81455f4f0ac80eda340bc3fa45831c7be1a8/src/Morph/Web/UserAgent02.qml:0) Uncaught (in promise) NotAllowedError: Write permission denied.`

**Comment by jonnius** [comment]
I confirm this works now (RC Xperia X).
