### ISSUE TITLE
javascript "console.debug()"-call in an html5-app breaks code-execution

### ISSUE THREAD

**Issue by luksus42** [ubports/morph-browser#39]
I have some debug outputs in my html5 app, but this seems to break the code execution.
For example, a button with a click handler and console.debug()-calls in it, throws error on click:
`file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Morph/Web/MorphWebView.qml:339: ReferenceError: sourceId is not defined`
and further handler execution is interupted.

I still need to confirm, that it is working without console outputs.

Full log, with some other issues regarding MorphWebView is here: https://paste.ubuntu.com/p/3kJ8s6t8Gw/
App for testing this (not published yet): https://github.com/luksus42/soundrecog/blob/master/build/soundrecog.luksus_0.2_all.click

**Comment by balcy** [comment]
you could already test it by changing /usr/lib/arm-linux-gnueabihf/qt5/qml/Morph/Web/MorphWebView.qml (requires read-write mount of / )

**Comment by luksus42** [comment]
Yes, changing sourceId to sourceID solves the issue.

**Comment by mariogrip** [comment]
Fixed by https://github.com/ubports/morph-browser/pull/41
