### ISSUE TITLE
unable to search from url bar

### ISSUE THREAD

**Issue by doniks** [ubports/morph-browser#4]
In the old browser (and in firefox on my desktop), I can type any term in the url bar and if that is not an actual url it will search for this term with my favorite search engine. 

The new browser instead tries to turn it into a hostname like http://SEARCHTERM.com

**Comment by doniks** [comment]
mhm. I'm pretty sure, this morning, after typing "telegram[ENTER]" it tired to load telegram.com, but if I try now, it doesn't do anything. just fills back whatever url was there before. 

However, still no search

**Comment by ruedigerkupper** [comment]
Confirmed. Entering a search term that is not a URL simply does nothing (it is not even converted to URL format. Simply nothing happens at all).

**Comment by ruedigerkupper** [comment]
Still present. Would be nice if this was fixed until xenial release. (Since the old browser is not working either due to memory problems.)

**Comment by TheUlpio** [comment]
With the old browser, typing few letters opens the dropdown list with two terms from history and other from google (in my case) search. Now i have to type a space after the few letters to open the dropdown lis, otherwise nothing happens unless a full url is typed. Is this annoying behaviour the same you are talking about?

**Comment by ruedigerkupper** [comment]
@TheUlpio Most probably. I simply had not discovered the "space trick".

**Comment by UniversalSuperBox** [comment]
The original issue in this bug is resolved, it is possible to search from the address bar. I will open another issue regarding the input box doing unexpected things.
