### ISSUE TITLE
custom player controls (html5 video) are not accessible in fullscreen mode

### ISSUE THREAD

**Issue by luksus42** [ubports/morph-browser#42]
When requesting a fullscreen in my html5-app (Plex) I  get this error in the log:
`file:///usr/share/morph-browser/WebViewImpl.qml:529: TypeError: Property 'fullScreenRequested' of object WebApp_QMLTYPE_72(0x1a24278, "webappBrowserView") is not a function`

The fullscreen does not get activated.
In the fullscreen-button onClick() method, I call `player.webkitRequestFullscreen()`. Where "player" is an html video element.

**Comment by luksus42** [comment]
Since latest devel (14.10.) the fullscreen gets activated.
But the indicator-bar is still visible, and the custom player controls are not accessible, but they are visible though.
So it seems, that the fullscreen is not a really a fullscreen.

**Comment by balcy** [comment]
yes I can confirm both, and have done some tests.
That the indicator is still visible should be possible to solve, the second problem with the player controls did show in the webapp and morph.
To see that I've "extracted" the player part of the app and let it run on a normal webserver.
With that I've seen the following:
- Chromium does not show any controls in fullscreen mode
- Falkon and Qutebrowser, which are both based on QtWebEngine, show the same behavior as morph.

Then I tried the example https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Audio_and_video_delivery/cross_browser_video_player (https://iandevlin.github.io/mdn/video-player/)
**No idea why they used that video... !? so I recommend only the other buttons but not play : )**
In fullscreen mode the controls are not clickable in Falkon, Qutebrowser and morph (and do not appear in Chromium)

So in the short term it might be needed to use the native player controls for the app (at least in full screen)... or someone comes up with a solution in morph : )

**Comment by luksus42** [comment]
Thanks for looking into this.

Using the native controls is or was not an option for me (and my app), because I needed to inject some special code to be able to make timeline-skipping work in a streamed video...

**Comment by mateosalta** [comment]
how did you solve hiding the indicator, when  tried setting the window to fullscreen in my webapp it crashed, https://github.com/mateosalta/cuddly-bassoon

**Comment by luksus42** [comment]
I didn't solve anything yet. Indicator is still visible, controls are not accessible.

**Comment by balcy** [comment]
this should fix the indicator-bar and progressbar, that still were visible in fullscreen mode.
https://github.com/ubports/morph-browser/pull/96
note that the custom controls are still not usable in fullscreen mode.

**Comment by luksus42** [comment]
I close this because it seems not be relevant anymore.
