### ISSUE TITLE
webapp-container / html5-app - navigator.mediaDevices.getUserMedia() not working

### ISSUE THREAD

**Issue by luksus42** [ubports/morph-browser#43]
Example app: https://github.com/luksus42/soundrecog/blob/master/build/soundrecog.luksus_0.2_all.click

When requesting UserMedia for audio-recording in this way:
 ``` javascript
navigator.mediaDevices.getUserMedia({ audio: true }).then(stream => {
     recorder = new MediaRecorder(stream);
     // function to be called when data is received
     recorder.ondataavailable = e => {
         [...some code...]
     };
}).catch(function(err){
     console.debug("ERROR on creating UserMedia: " + err);
});
```
It always hits the catch-block, with error: `NotReadableError: Could not start source`

When the same code is executed by the Morph-Browser, the code is working.
^^ Tested by creating a python http.server in www-directory of the app (`$ python3 -m http.server 8000`) and then opened http://localhost:8000 in the Morph-Browser.

**Comment by balcy** [comment]
it also does not work, if you run the http server, and change the URL in the desktop file to http://localhost:8000
I get `qml: [JS] (http://localhost:8000/js/application.js:76) Uncaught TypeError: Cannot read property 'state' of undefined`  may be a permission problem of webapp-container ?

**Comment by luksus42** [comment]
Yes, There are a lot of issues with the webapp-container. Thats why I suggested to use the morph-browser for a positive-test, which shows, that the browser is able to do this things in general.

**Comment by luksus42** [comment]
> may be a permission problem of webapp-container ?

I don't think so, because launching the app with apparmor template "unconfined" does not work either.

**Comment by balcy** [comment]
at least one of the problems was, that for some reason the user was not asked for the microphone permission, see https://github.com/luksus42/soundrecog/pull/1

**Comment by balcy** [comment]
what I've tested is putting the content in `www` to a real webserver, and changed the URL in the desktop file to it. (it still did not work).
Then I just changed URLs of other installed webapps to that server URL, and they asked for the microphone permission.
But I still have not fully understood, if only the manifest file change or the missing icon was the problem, but at least with the change I could get it to the point that it asked the user.

**Comment by luksus42** [comment]
Thanks for your investigation.
I never experienced the absence of the "microphone-permission-question".
But anyway, even if I've been asked for it, the webapp is not capable of creating the UserMedia object.

I recently added try catch block and a debuglog for that issue:
https://github.com/luksus42/soundrecog/commit/fda979bd3b446c6570a762d4fa781ee71c80af55

And still, if I start a python webserver in the www directory of the app, it is working when calling the localhost:port with the morph browser. It is recording and sending a request to acrcloud server.
(Another problem here is the "missing 'Access-Control-Allow-Origin' header".)

**Comment by luksus42** [comment]
So I played with the qtWebEngine-Example (https://gitlab.com/ubports/app-dev/qt-webengine-demo) and got it working. https://github.com/luksus42/soundrecog/commit/37a87a7be69b2ef0157d112bf892672445644ba5
Perhaps the webapp-container needs a similar approach on granting a requested feature?

**Comment by balcy** [comment]
see the picture in https://github.com/luksus42/soundrecog/pull/1, before that change the microphone permission was not requested
(not the popup that asks for the microphone access  for the current domain, but the one for the general permission shown in the screenshot)
So if the webapp-container works with  the changed manifest and icon I would close this issue.

**Comment by luksus42** [comment]
Ahhhh... Ok I think my app permissions were just messed up or smething...
So I created a fresh app with a different app_name to confirm your findings and have to say: you are right!
The solution is mainly the missing picture.
(Therefore I could have saved myself my yesterdays investigations with the qml app...)

Anyway, thank you very much.
Perhaps this behaviour should be documented somewhere?

**Comment by balcy** [comment]
maybe the QML app can be useful in the future for more flexibility : )
I think it is kind of a bug too, that the permission dialog needs a picture to appear. (I've not looked into system logs for this)
