### ISSUE TITLE
Error regarding the certificate of a website

### ISSUE THREAD

**Issue by Bsoupe** [ubports/morph-browser#432]
When opening the page https://linuxnews.de I get an error regarding the certificate of this page, which points to the test page. 

This error occurs repeatedly on the following devices: Volla Phone & BQ Aquaris M10 HD both with OTA-15.

**Comment by balcy** [comment]
the page https://test.linuxnews.de/ does really not have a valid certificate, it looks like it has not been created for subdomains (e.g. *.linuxnews.de wildcard) but just for the main domain. I  don't know why linuxnews.de does access test.linuxnews.de, IMHO the website needs to be fixed here.

**Comment by Bsoupe** [comment]
But I don't enter subdomains. Test site isn't in use. No other browser noticed that! If I enter https://linuxnews.de the browser shouldn't ask for subdomain certificates or am I wrong?

**Comment by balcy** [comment]
the problem of the site seems to be the icon of the RSS feed on the right:
![image](https://user-images.githubusercontent.com/848115/103211431-79628d80-4908-11eb-806a-3a211044285d.png)
```
<a href="/feed/" title="Linuxnews - Abonnieren Sie unseren Newsfeed">
<img src="https://test.linuxnews.de/wp-content/themes/tortuga-child/images/linuxnews-rss-icon.png" alt="Linuxnews - RSS-Icon" />
</a>
```
Firefox for example does not display an error message, but just ignores the resource.

**Comment by balcy** [comment]
update: the site just seems to have corrected the link, and now the icon is displayed. 
![image](https://user-images.githubusercontent.com/848115/103212809-2ee31000-490c-11eb-9535-8b5a59962580.png)
The error should no longer be present in morph. The feed itself seems to be broken, too, but that's another issue.

**Comment by balcy** [comment]
ok, yesterday I've seen the error on BQ Aquaris 4.5 dev, now it is no longer present.
Can you confirm it is no longer there on your device ?

**Comment by Bsoupe** [comment]
Yes, correct. Thank you!
