### ISSUE TITLE
Chromium Web Security breaks HTML5 apps with WebEngine

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#44]
today I've upgraded to latest RC (W41) and the RSS reader app did no longer show feeds.
https://open-store.io/app/rssreader.florisluiten
I can post logs later, I saw apparmor messages and some other entries regarding morph-browser

**Comment by balcy** [comment]
the app is HTML based

**Comment by balcy** [comment]
startup log:
https://pastebin.ubuntu.com/p/SNZcSdsq5D/

adding a feed:
``qml: [JS] (file:///opt/click.ubuntu.com/rssreader.florisluiten/0.2.4/www/index.html:0) Failed to load https://puri.sm/feed/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'file://' is therefore not allowed access.``
This might be because of the new chromium version: no access from file:// to http(s):// urls and vice versa. (security)

The app is html5 and the desktop file has the command `webapp-container ./www/index.html`

**Comment by dobey** [comment]
It looks like webapp-container will likely need to grow a command line option equivalent to chromium's `--disable-web-security` option, so that HTML5 apps will be able to talk to remote services. However, this will also open up the possibility of remote content being able to do things with `file://` URIs as well.

**Comment by balcy** [comment]
ok I will open another issue for the startup problem (access permission to folder) seen in the pastebin

**Comment by dobey** [comment]
There is already an issue open for that problem, I think against apparmor-easyprof-ubuntu.

**Comment by balcy** [comment]
Ok I will mention it there, then one of them can be marked as duplicate, thanks !

**Comment by mateosalta** [comment]
does this have anything to do with remote content blocked for a local html?  http://doc.qt.io/qt-5/qwebenginesettings.html
QWebEngineSettings::LocalContentCanAccessRemoteUrls

**Comment by dobey** [comment]
It seems like that might solve this @mateosalta if it were hooked up to a CLI option in webapp-container, so that individual apps can specify if they need to.

**Comment by mateosalta** [comment]
Ah, that sounds good. that way we can leave the regular browser with the default.

**Comment by balcy** [comment]
good news,  settings.localContentCanAccessRemoteUrls: true
solves the problem for RSS reader, now we only need to make it configurable as dobey proposed.

**Comment by tjrhodes** [comment]
Device: FP2
System Build: 2018-W48

Issue solved I think. RSS Reader and a couple of other webapps load fine and run ok.

**Comment by balcy** [comment]
are you using https://open-store.io/app/rssreader.florisluiten ? This can load, but new feed contents / new feeds can only be loaded with an updated version of RSS Reader that uses the new flag.
Floris will update the version in open store after doing some other changes (https://github.com/florisluiten/rssreader/pull/12)
Normal webapps have not been affected by this problem (only ones with local html), but for example https://open-store.io/app/utmedia.nfsprodriver already does use the new flag
