### ISSUE TITLE
QtQuick Controls 2 Style isn't Suru

### ISSUE THREAD

**Issue by kugiigi** [ubports/morph-browser#440]
I saw that `QT_QUICK_CONTROLS_STYLE` is being set to `Suru` in the code however, it doesn't seem to take effect on QQC2 components. A sample I tried is `Menu` which looks like styled with the `Default` style.

Here's a sample screenshot. (Ignore the wrong orientation, it's another issue that seems to affect `Menu` :sweat_smile: )
![image](https://user-images.githubusercontent.com/29456786/103464176-9d8cf700-4d6c-11eb-96fa-aa4a2eeab9f9.png)

**Comment by balcy** [comment]
confirmed, it used to work when https://github.com/ubports/morph-browser/commit/be1e92350484933ee875b2f62b6e2b68855b7c65 was added, but stopped a few weeks / months ago, I cannot really say when.
(the same behavior is seen for the zoom selector in the settings page, it looks like QQC default style now)

**Comment by kugiigi** [comment]
Oh yes, I thought only the swipe delegates were qqc2. I have a build from 05/27/2020 on my Nexus 5 and the zoom control is already styled with the default styling. So looks like this regressed a long time ago :sweat_smile:
