### ISSUE TITLE
morph can't keep screen on when playing videos

### ISSUE THREAD

**Issue by j2g2rp** [ubports/morph-browser#449]
devices: N5 and M10FHD
channel: devel

Looks like morph can't keep screen on when playing videos, it  is happening from some updates ago (maybe 3 or 4 days ago).

**Comment by FlavioMala** [comment]
Confirmed (e.g. "Youtube") on my BQ E5 ch. dev

**Comment by dobey** [comment]
This should be fixed in devel now, with the rebuild of qtsystems packages.

**Comment by FlavioMala** [comment]
Now it is OK on my BQ. Thanks!

**Comment by dadandalive** [comment]
I confirm, when playing a Youtube video in Morph (on Nexus 5 RC 2021-W10) that lasts longer than the Settings' inactivity timeout threshold and without providing any other user input, display stays active (and, obviously, Morph suspension prevention was not activated in the tweakapp).
