### ISSUE TITLE
Missing letters

### ISSUE THREAD

**Issue by donno2048** [ubports/morph-browser#451]
# Missing letters

- The emoji list missing combinations, for example: :man_technologist: and :woman_technologist: are shown as: :man:💻 and :woman:💻 respectively.
- Some letters like the ole character  " ֫ " and the Arabic "﷽" cannot be rendered.

Edit: This issue as viewed from ubuntu touch:
![ScreenShot](https://user-images.githubusercontent.com/61805754/105923346-e9b61900-6044-11eb-9c6c-07a367e7cf23.jpeg)

**Comment by mateosalta** [comment]
emoji needs updating, I was testing this but unfortunately the new emoji color sets are not supported by qt and the browser yet. I also looked into the formats that are supported, hopefully we can update :) 
![screenshot20210126_200211228](https://user-images.githubusercontent.com/1965279/105931801-78a93e00-6011-11eb-854a-4c446b0afbea.png)


 . See: https://github.com/ubports/keyboard-component/issues/1 

And if you want the full emoji set (although only black/white) follow:

You won't be able to type the new ones, until they are added to the keyboard, but until then you can at least see when someone sends you one

download the deb on top https://github.com/eosrei/twemoji-color-font/releases

mount filesystem r/w

sudo apt install ttf-bittstream-vera

sudo dpkg -i

on the deb file wherever you put it

and reboot :)

**Comment by donno2048** [comment]
Good to know, thanks for the quick response!

**Comment by donno2048** [comment]
> mount filesystem r/w

Was that supposed to be :

```bash
sudo mount filesystem -o remount,rw /
```
?

**Comment by mateosalta** [comment]
sudo mount -o remount,rw /

or with uttweak tool from the openstore

**Comment by mateosalta** [comment]
Hopefully I can work on the color formats, right now I found a unicode 11 font (from my picture) but need to specify it as the primary font somehow, and get the unicode 13 converted somehow, I did see a conversion application on github
