### ISSUE TITLE
I Can't implement WebChannel caused by: "QWebChannelAbstractTransport not found"

### ISSUE THREAD

**Issue by fulvio999** [ubports/morph-browser#454]
I'm updating an App  (QML, html,js)  removing dependency from Oxyde to Morph.web. Trying to implement Html <--> QML communication, as described here: https://retifrav.github.io/blog/2018/07/14/html-from-qml-over-webchannel-websockets/ (Section "Mostly QML") 
Running "clickable desktop" i got the message:
_fatal error: QWebChannelAbstractTransport: No such file or directory
compilation terminated._
Are missing some stuff in Morph.web  to have Html <--> QML communication ? 
Also see the discussion at: [https://forums.ubports.com/topic/5395/migration-from-oxide]()

Thanks

**Comment by kugiigi** [comment]
Have you tried deploying to device?
I've had issues lately running apps on the desktop so this may be an issue with clickable.

**Comment by fulvio999** [comment]
Is not possible, the error happen at compile time. If somewhere there is an App that already uses WebChannel i can test it.
Thanks

**Comment by balcy** [comment]
it is only a guess, but it sounds like the header file is not found.
Do you use `#include <QWebChannelAbstractTransport>` ?

have you tried changing it to `#include <QtWebChannel/QWebChannelAbstractTransport>`

It might help finding the file. First I thought it is needed to add the dependency "libqt5webchannel5-dev" to clickable, but it is already installed in the clickable images.

**Comment by fulvio999** [comment]
Your guess was correct,   the correct import is:
#include <QtWebChannel/QWebChannelAbstractTransport>. (my import was without "QtWebChannel/" prefix)

Now the project build and start, But fails when try to load the plugin:
`qrc:/Main.qml:25:1: plugin cannot be loaded for module "TransportPlugin": Cannot load library /home/fulvio/Scrivania/testWebChannel-main/build/x86_64-linux-gnu/app/install/lib/x86_64-linux-gnu/TransportPlugin/libTransportPlugin.so`

Same error when running 'clickable desktop' o running on device. 
I don't know if is a bug or my fault.
My basic test project is here: [https://github.com/fulvio999/testWebChannel]( https://github.com/fulvio999/testWebChannel)
created with clickable.
Thanks

**Comment by balcy** [comment]
Hi it helped moving the implementation of webSocketTransport.h to its own cpp-File. https://github.com/balcy/testWebChannel/commit/2765c8d7e30ee11e090c9eb91bae2efc811b8889

So that error is gone now, but there is still / now the error `qrc:/Main.qml:77:9: WebSocketServer is not a type`

**Comment by balcy** [comment]
moved to https://github.com/fulvio999/testWebChannel/issues/1
