### ISSUE TITLE
Preview of tabs sometimes are gone when switching between tabs

### ISSUE THREAD

**Issue by kugiigi** [ubports/morph-browser#457]
### Steps to Reproduce
1. Switch to the second tab
2. Switch to the 3rd tab
3. Open the tab switcher

### Expected Results
Previews of all tabs you switched to are displayed

### Actual Results
Preview of the 3rd tab in the list is blank and shows an error in the log
```...TabPreview.qml:122:13: QML QQuickImage: Protocol "itemgrabber" is unknown```

### Additional Information
- Reopening the app restores the missing preview
- It seems that this error was introduced in Qt5.12
- It seems to only happen with previews created with `grabToImage` and whenever the preview is unloaded in the view due to scrolling or model change.

**Comment by Fuseteam** [comment]
confirmed the third preview in the tab list is unloaded

**Comment by dano6** [comment]
This is a regression, I am looking into how to make propper fix. They improved garbage collecting in 5.12, it is dereferencing image due memory saving.

**Comment by kugiigi** [comment]
The reference to the grabToImage result is already stored as a property of `BrowserTab` but I guess that's not enough on 5.12 anymore.
I developed a workaround which uses the preview stored as file whenever the this issue happens but maybe there's a better solution?

**Comment by CDLProduction** [comment]
Tested on redmi note 7 lavender on current rc version 2021-w08
Tested on 6 tabs and switching between them, all preview are displayed.

**Comment by Fuseteam** [comment]
I can confirm preview works on all tabs that were switched to on vegetahd on devel 2021-02-23

**Comment by cibersheep** [comment]
Looks fixed on E5

**Comment by dadandalive** [comment]
I confirm all 3 tab previews are shown in the tab switcher on N5 RC 2021-W10.

**Comment by ghost** [comment]
I confirm all 3 tab previews are shown in the tab switcher on BQ Aquaris E4.5 RC 2021-W10
