### ISSUE TITLE
html5 app cannot access .local/share/<app> folder

### ISSUE THREAD

**Issue by balcy** [ubports/morph-browser#46]
today I've upgraded to latest RC (W41) and the RSS reader app did no longer show feeds.
https://open-store.io/app/rssreader.florisluiten

The app starts but the list of feeds is not loaded.

startup log:
https://pastebin.ubuntu.com/p/SNZcSdsq5D/

It seems no longer possible to access the share folder:

```Cannot create directory file:///home/phablet/.local/share/rssreader.florisluiten. Error: FILE_ERROR_ACCESS_DENIED.```

in the beginning there are apparmor messages, but I'm not sure if they matter here
```error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.270\" (uid=32011 pid=26152 comm=\"webapp-container ./www/index.html \") interface=\"com.canonical.libertine.Service.Operations\" member=\"list\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3480 comm=\"/usr/bin/python3 /usr/bin/libertined \")"```

**Comment by balcy** [comment]
@dobey pointed out this is likely a duplicate of https://github.com/ubports/apparmor-easyprof-ubuntu/issues/7

**Comment by mariogrip** [comment]
This should be fixed by: https://github.com/ubports/morph-browser/commit/02fffeb661abb13d3f5c7d5f1559e3790b1fd1a0
