### ISSUE TITLE
Download Icon Too Big

### ISSUE THREAD

**Issue by cibersheep** [ubports/morph-browser#461]
The new download icon in header is a bit too big

![imatge](https://user-images.githubusercontent.com/6640041/107894825-49f7f680-6f31-11eb-85ec-6620c8cb7ade.png)

Sorry @kugiigi ^__^

**Comment by kugiigi** [comment]
You are right, didn't notice that.
It's weird though since they are set with the same size. I guess the UITK icons doesn't have the same height :sweat_smile: 
I'll try to experiment with the height :smiley:

**Comment by kugiigi** [comment]
Try #462 if it's good enough :)

**Comment by cibersheep** [comment]
Do you have a screenshot? I can't install via `ubports-qa`

**Comment by kugiigi** [comment]
![screenshot20210215_190052915](https://user-images.githubusercontent.com/29456786/107938389-48294400-6fc0-11eb-8b57-a614343d324a.png)

**Comment by cibersheep** [comment]
Thanks a lot.
Look perfect to me :)
