### ISSUE TITLE
white area overlaying browser

### ISSUE THREAD

**Issue by doniks** [ubports/morph-browser#5]
repro:
open forums.ubports.com
tab into any text field, like login, or search

observe:
there is a white area blocking out part of the browser.
the size of the area looks suspiciously identical to the size of the keyboard

device:
nexus 7 deb
xenial
![keyboard](https://user-images.githubusercontent.com/26801304/40930920-659fcf00-6829-11e8-915f-d884492e52f7.png)

**Comment by doniks** [comment]
happens on all textfields on all websites 
happens also when entering URL
does NOT happen in desktop mode!

**Comment by Trim** [comment]
Hello,

I've just installed 16.04 W26 and the browser-ng: I notice the same issue on an aquaris m10 (cooler) device.

For me, it's like if the white part should be place for the keyboard.

It seems for me that the OSK is a little bit more compact on 16.04, maybe, the issue is just about the expected heigh of the OSK ?

**Comment by hummlbach** [comment]
The same on mako. Unfortunately here the osk takes half of the screen s.t. the other half is blank.

**Comment by advocatux** [comment]
I can reproduce this issue too on BQ E4.5 (krillin) running UT 16.04 (2018-07-01), with the only difference that it's even worse on this device

![browser-ng](https://user-images.githubusercontent.com/30233652/42163371-82de0638-7e02-11e8-923f-49665babdcdb.jpg)

**Comment by ruedigerkupper** [comment]
This really is a show stopper. It renders browser next unusable.

**Comment by mateosalta** [comment]
seems like the keyboard avoidance went wrong somewhere, I fixed by removing this on the youtube webapp I'm working on - but then content does flow under the keyboard (nice for transparent keyboard) this is ok for youtube, but I know some sites the keyboard will cover the textfield. 

Would this situation be better than the white box?

**Comment by cyberpunkedu** [comment]
I'm getting something similar in Morph in webapps using the ogra container. The page loads, then it goes all white, but it seems unrelated to the keyboard.

**Comment by ruedigerkupper** [comment]
Confirming the problem that userj reports (webapps using the ogra container turn completely white after loading). But I'm not sure it is really the same thing as the white keyboard overlay.

**Comment by mateosalta** [comment]
yeah, they are crashing because they are on the old browser using oxide. not related.

**Comment by cyberpunkedu** [comment]
> yeah, they are crashing because they are on the old browser using oxide. not related.

I modified the container to use Qtwebengine
`import QtWebEngine 1.7 as Morph`

But it still shows up white after loading. It did work once or twice.

**Comment by mateosalta** [comment]
oh cool, do you have the click, or the container code anywhere, @userj we have been wanting to work on a new container based on ogra - any progress you have would be helpful

**Comment by cyberpunkedu** [comment]
@mateosalta this is the "ogra" code that I used https://gitlab.com/joboticon/paybyphone . I modifed the Main.qml to import QtWebEngine as "Morph" (arbitrary variable name) then replaced the calls to "Oxide" as "Morph" . I'm not sure if this is the right way, but it seemed to work a bit.

**Comment by doniks** [comment]
I'm not sure about all of the latest comments, but *my* issue is fixed. If something is still faulty for any of you guys, probably best to open a new issue with clear reproduction
