### ISSUE TITLE
Content hub not working

### ISSUE THREAD

**Issue by YougoCodes** [ubports/morph-browser#51]
device: fairphone 2
os: ubports Ubuntu touch 16.04/rc (2018-w41/2)

steps to reproduce with full browser or with webapp
1. open morph browser
2. load a website with upload function, like a webmail compose page or Whatsapp web
3. choose attach or upload a file
4. content hub loads

expected behavor:
5. choose app, select content, confirm
6. content app closes, content hub closes
7. file is uploaded

actual behavior:
for webapp
5. choose app, select content, confirm
6. content app closes, content hub closes
7. nothing is uploaded, no indication of an error

for full browser
5. icons in content hub are unresponsive. 
6. content hub does scroll and can be cancelled
7. nothing is uploaded

Willing to provide logs, test settings and .click apps

**Comment by balcy** [comment]
I can confirm this, unfortunately. ( bq Aquaris 4.5)
Up to now I had the click package of morph browser installed which masked the error for me.
After removing the click package I got the described behavior in morph-browser.

**Comment by balcy** [comment]
```Oct 14 15:58:24 bq dbus[2015]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/transfers/morph_2dbrowser/import/195" interface="com.ubuntu.content.dbus.Transfer" member="State" mask="send" name="com.ubuntu.content.dbus.Service" pid=799 label="morph-browser" peer_pid=3431 peer_label="unconfined"```
I get this in the syslog. Note: Sharing does not work either.
E.g On the home page click Share in the menu, then on Messaging app icon, the current url is not shared, but the share menu just closes.

**Comment by balcy** [comment]
@YougoCodes can you test the file upload again with the latest RC ?

**Comment by balcy** [comment]
please reopen if still a problem on RC or devel

**Comment by Talkless** [comment]
Does this issue covers copying selected text? I cannot copy selected text (there's no Copy item in the popup) after upgrading OTA-3 -> OTA-5:
![screenshot20181124_132615516](https://user-images.githubusercontent.com/292191/48967675-222cb900-efdc-11e8-8e43-a33dda8a5265.png)

**Comment by balcy** [comment]
yes on RC it looks like this:

![image](https://user-images.githubusercontent.com/848115/48967987-0ed41a80-efe9-11e8-8f35-9da036787fd6.png)

**Comment by Talkless** [comment]
@balcy Cool, thanks!

**Comment by ghost** [comment]
device:Nexus 5
channel: RC 2018-W48
issue solved. Unable to reproduce. Tested on Dropbox and personal server.

**Comment by tjrhodes** [comment]
Device: FP2
System Build: 2018-W48

Issue Solved, uploaded files successfully to a nextcloud box.
