### ISSUE TITLE
Change homepage dialog scrolls off screen when keyboard appears

### ISSUE THREAD

**Issue by Lyokanthrope** [ubports/morph-browser#52]
Device: Hammerhead/Nexus 5
OS Build number: 2018-10-13 (16.04, devel channel)

Steps to reproduce:
1. Open Morph browser
2. Hamburger button > Settings
3. Tap 'Homepage' 

Expected behavior: For the dialog to not get scrolled off screen

Actual behavior: Dialog scrolls off screen when onscreen keyboard appears.

[Video of the problem occuring](https://i.imgur.com/St2ditp.mp4)

**Comment by balcy** [comment]
All popup dialogs were affected. e.g. the java script prompt dialog.
For testing I made the dialog take the whole screen, and opened the keyboard.
There you see that the dark area gets larger much faster (twice as much on my phone) as you move up the keyboard.
![dialog_osk](https://user-images.githubusercontent.com/848115/47951503-d00af180-df61-11e8-8116-16974deed54e.png)

**Comment by toehold** [comment]
Fixed on N5, Ubuntu 16.04 (2019-W09)

**Comment by jezek** [comment]
FP2 (2019-W09)
The home page dialog stays on always screen (portrait/landscape).

**Comment by ziggutas** [comment]
Nexus 7 flo (2019-W09) works properly

**Comment by mattbel10** [comment]
I cannot reproduce the described issue, therefore it is fixed thanks to @balcy 

Device: Meizu Pro5
Build: Ubuntu 16.04 (2019-W09)

**Comment by haeckle** [comment]
Fixed on Nexus 4 with 2019-W09

**Comment by erik-kueng** [comment]
FP2
2019-W09
could not reproduce issue

**Comment by ziggutas** [comment]
BQ E4.5 2019-W09
Dialog box, osk stay onscreen
