### ISSUE TITLE
WebRTC unmasks VPN revealing true IP

### ISSUE THREAD

**Issue by electricbrain-code** [ubports/morph-browser#521]
Morph Browser's WebRTC unmasks VPN revealing true IP.
https://browserleaks.com/webrtc
Can WebRTC be disabled by the user?

**Comment by mateosalta** [comment]
Possible duplicate of: https://github.com/ubports/morph-browser/issues/257

**Comment by electricbrain-code** [comment]
Sorry, yes correct - this is a duplicate.
