### ISSUE TITLE
prevent suspension

### ISSUE THREAD

**Issue by Gabriele69** [ubports/morph-browser#55]
The browser is integrated into the operating system, so it is not possible to prevent background suspend (for example with UT Tweek Tool). The option must be entered in the settings. Gabriele

**Comment by dobey** [comment]
As it appears webbrowser-app did in fact appear in Tweak Tool, it's most likely that it's added manually to a list, and that list needs updating in Tweak Tool.

**Comment by Gabriele69** [comment]
Hi dobey
I can not add it manually in UT Tweek Tool. Morph-Browser is not an app contained in the Open Store. With UT Tweak Tool, I can only add the launcher to my favorite apps.

I forgot: I use the BQ E4.5 with UT 16.04 Dev (10/14/2018)

**Comment by dobey** [comment]
Right. What I'm saying is that the old browser was in the tool, but it's also not a click from the store. I think this is something that should be fixed in that tool, not in the browser itself.

**Comment by UniversalSuperBox** [comment]
Looks like that is correct. UT Tweak Tool mentions webbrowser-app specifically at a few points: https://github.com/sverzegnassi/ut-tweak-tool/search?q=webbrowser&unscoped_q=webbrowser

I'm not sure if UTTT is being maintained anymore, but you will want to file a bug there.

**Comment by mateosalta** [comment]
I think he is still around, he did work on the qtquick controls theme. I put a pull request in: https://github.com/sverzegnassi/ut-tweak-tool/pull/5
