### ISSUE TITLE
URL input box should not have autocorrect

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/morph-browser#56]
In the browser, the URL bar currently has autocorrect enabled:

![screenshot20181016_074606182](https://user-images.githubusercontent.com/21966173/47017464-f33b4180-d117-11e8-98c7-bd1a2ac49d7f.png)

This causes several problems, for example:

* Input isn't actually passed to the box until the keyboard is finished with the word, so autocomplete doesn't start until the user selects an autocorrect word or presses Space
* URLs aren't normally perfect for the language you're native to. The keyboard "helpfully" trying to correct them is annoying ("google.com can become Gogol. com")

## How to fix it

Set the [inputMethodHint](https://api-docs.ubports.com/sdk/apps/qml/Ubuntu.Components/TextField.html#sdk-ubuntu-components-textfield-inputmethodhints) to `Qt.ImhNoPredictiveText` in [AddressBar.qml](https://github.com/ubports/morph-browser/blob/xenial/src/app/webbrowser/AddressBar.qml). Note that you can set multiple input hints on one widget by adding a bar (`|`) between the values.

**Comment by ghost** [comment]
device:Nexus 5
channel: RC 2018-W48
issue solved. Unable to reproduce

**Comment by Ingo-FP-Angel** [comment]
device: FP2
channel: RC 2018-W48
Issue solved. Unable to reproduce.
