### ISSUE TITLE
Cannot follow links with target="_blank"

### ISSUE THREAD

**Issue by doniks** [ubports/morph-browser#6]
Repro:
go to ubports.com
tap the "burger" menu
-> folds out - OK
tap "COMMUNITY"
-> folds out - OK
tap "Forum"
-> nothing happens - NOT OK - expect to open new tab with forum
tap "FAQ"
-> navigates to FAQ - OK 
 

"Documentation" doesn't work either. Maybe it doesn't support "open in new page"?

On ubports.com I cannot open the link under -> Community -> Forum, nor Documentation

**Comment by advocatux** [comment]
I think the browser doesn't know how to handle `target="_blank"` tag.

To make the issue worse, the browser doesn't show a context menu when pressing a link either.

**Comment by hummlbach** [comment]
confirmed on mako 16.04 rc with startpage.com. Changing the startpage settings to not open the search results in new window/tab makes the links working.

**Comment by balcy** [comment]
is now part of https://github.com/ubports/browser-ng/pull/16

**Comment by ruedigerkupper** [comment]
Still present. Would be nice if this was fixed until xenial release. (Since the old browser is not working either due to memory problems.)

**Comment by doniks** [comment]
fixed
