### ISSUE TITLE
Browser does not restore previous session at startup

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/morph-browser#60]
Moved from https://github.com/ubports/ubuntu-touch/issues/913

The browser doesn't open previous web pages closed recently, even this setting is activated and the browser was closed with some pages opened. This means, that the browser always opens with homepage.

**Comment by balcy** [comment]
there is a branch xenial_-_sessionrestore that is not yet merged. (I don't know if it is complete there)

**Comment by ruedigerkupper** [comment]
Duplicate of #8?

**Comment by UniversalSuperBox** [comment]
Indeed!
