### ISSUE TITLE
Meizu Pro Scall Browser

### ISSUE THREAD

**Issue by Billdemoncho** [ubports/morph-browser#61]
Hello on my Meizu pro 5, the Browser Morph application is too small.
It does not take the full width and height of the screen
How to manage this ?
I am in 16.04 dev

![screenshot20181016_201930133](https://user-images.githubusercontent.com/42817545/47038897-e0aa2200-d182-11e8-8f6f-6b67e27f8e59.png)

**Comment by UniversalSuperBox** [comment]
Have you updated recently @Billdemoncho? This should have been fixed prior to the OTA-5 release.

**Comment by Billdemoncho** [comment]
After the update, it's perfect
closed file

**Comment by mateosalta** [comment]
seems to be a 1 pixel white border on the right, almost perfect :)
