### ISSUE TITLE
Cannot paste to empty space

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/morph-browser#66]
In text boxes, I seem to be unable of pasting text. (Example: GMail website, composing a message
Long-pressing an empty portion of the text box does *not* bring up the paste dialog.
Workaround: type some characters at the point where you want to paste text. Long-press them, chose paste: Pasted text replaces the characters. But this can't be the intended way.

**Comment by balcy** [comment]
This I cannot confirm right now, I did have problems with the "copy" not appearing, but the paste works for me for empty textareas / inputs.

**Comment by balcy** [comment]
if you are on RC or devel, do you still have the problem?

**Comment by balcy** [comment]
please reopen if the issue is still present on RC or devel

**Comment by ruedigerkupper** [comment]
Appears fixed, but I'm on devel on an Xperia X.
Thanks!
