### ISSUE TITLE
Browser does not handle SSL certificate errors

### ISSUE THREAD

**Issue by joolz** [ubports/morph-browser#70]
I have problems opening sites with a self signed ssl cert. I know I can get a cert but I don't need one, I'm the only user. I can fetch the https page with wget but Morph just gives me a blank page, no error message. The page opens correctly on chrome on a recent Android (after a certificate warning)

More people have this issue, see https://forums.ubports.com/topic/1830/morph-browser-on-ota-5-no-self-signed-certs

**Comment by mateosalta** [comment]
there was a flag you could  use for your own app, ill have to see if that was only oxide.

**Comment by balcy** [comment]
I'll send a PR for this soon

**Comment by UniversalSuperBox** [comment]
Closed by #73

**Comment by ghost** [comment]
device:Nexus 5
channel: RC 2018-W48
issue solved. Unable to reproduce with multiple test sites using self signed certs.
