### ISSUE TITLE
Standby mode while video playback

### ISSUE THREAD

**Issue by YugiFanGX** [ubports/morph-browser#71]
When I play videos on the current browser, the playback stops after the defined standby timer (default 1 min)

**Comment by ropod7** [comment]
The same issue on my device. Installed OTA-5 through the ubports-installer on the already exists home directory.

**Comment by mateosalta** [comment]
we could configure screensaver off on certain conditions + the keep display on permission

**Comment by mateosalta** [comment]
basicallt what active screen does but put in condition that app is active and video playing

**Comment by balcy** [comment]
Yes it is technically possible to do that. (the permission is already present)
What would be good as a condition ?
For example there is the information, if audio has been played recently: https://doc.qt.io/qt-5/qml-qtwebengine-webengineview.html#recentlyAudible-prop
Another possibility would be turning the screen saver off whenever full screen is active. (or for each of those)... or something else ?

The audio condition would mean, that the device keeps on all the time, if you listen to a internet radio stream. 
Maybe we should make the "keep on for audio and full screen" configurable in the browser settings.

**Comment by mateosalta** [comment]
that sounds good, as I often watch youtube videos on mute with captions, so either fullscreen or audio  would work

**Comment by Ingo-FP-Angel** [comment]
Device: FP2
Channel: RC
Version: 2018-W01

I cannot reproduce the issue, i.e. the fix works.

**Comment by advocatux** [comment]
Device: Nexus 5 (hammerhead)
Channel: RC
Version: `2018-W01` (_really_ `2019-W01`)

Fix works. I can't reproduce this issue anymore.

**Comment by 10JML01** [comment]
Device: BQ M10FHD
Channel: rc
Version: 2018-W01

Fix works, screen won't lock or go dark during Youtube Videos.

**Comment by erik-kueng** [comment]
Fairphone 2
rc
2018.W01

Fix works. Could not reproduce issue.
