### ISSUE TITLE
Restore previous session - does not work 

### ISSUE THREAD

**Issue by doniks** [ubports/morph-browser#8]
Repro:
go to settings
confirm that "Restore previous session at startup" is ticked 
open a couple tabs
swipe in from the right
swipe the browser down to close it
open the browser again 

Expected:
the tabs from previous session are restored 

Actual:
Only one tab with search engine opens

**Comment by tatonuta** [comment]
The same problem on:

    Device: Krillin - Bq Aquaris E4.5
    Channel: 16.04 RC
    Build: 2018-W27

**Comment by ghost** [comment]
device:Nexus 5
channel: RC 2018-W48
issue solved. Unable to reproduce, tested with up to 7 tabs open.

**Comment by UniversalSuperBox** [comment]
Session restore works on my Nexus 7 (flo), Nexus 5, and Fairphone 2.

**Comment by MEstner** [comment]
Fixed in 2018-w48 in m10 FHD
Unable to reproduce
