### ISSUE TITLE
Https errors go just blank 

### ISSUE THREAD

**Issue by xqqy** [ubports/morph-browser#82]
Using 16.04ota5 in nexus7. stable 
Of crouse morph-browser does not trust my self-signed cert. But different from Firefox or chrome. It just go blank and not show any warning or help information.
I think a help page is necessarfory.  And it can be better to let me choose continue browse or not.

**Comment by balcy** [comment]
sounds like https://github.com/ubports/morph-browser/issues/70 which is fixed in devel
