### ISSUE TITLE
Find functionality does not work

### ISSUE THREAD

**Issue by kugiigi** [ubports/morph-browser#87]
## Steps to Reproduce
1. Open the Morph Browser
2. Go to the "Find in page" option
3. Type a word that is in the currently loaded page.

## Expected Result
The find count should be equal to the matching words of the typed word and the word should be highlighted.

## Actual Results
The find count is always zero and not words are highlighted even if the word is obviously in in the page

**Comment by balcy** [comment]
find in page was implemented recently in devel / RC
note: there are no more counters, because the QtWebEngine just does offer a findText method with a boolean result, if a match was found.

**Comment by balcy** [comment]
solved with https://github.com/ubports/morph-browser/pull/81

**Comment by lionelb123** [comment]
Tested on FP2 and BQ FHD both on rc 2018-48
Works perfectly on both
With the implementation, highlighting begins with the first letter typed, so searching for 'butter' highlights all instances of b, then bu, then but etc. That is a bit disconcerting but an advantage for anyone who has difficulty with spelling - or indeed finding a word even where it has been spelt incorrectly on the page!

**Comment by ghost** [comment]
device:Nexus 5
channel: RC 2018-W48
issue solved. Unable to reproduce

**Comment by andrisk-dev** [comment]
Device:Nexus 5
Build: 2018-W48
Issue solved - searched words are highlighted on website and by clicking enter I can cycle through the words.
