### ISSUE TITLE
No 'open in new tab' context menu

### ISSUE THREAD

**Issue by doniks** [ubports/morph-browser#9]
Reproduce:
github.com
long press a link

Observed:
nothing happens

Expected:
context Menu opens and I can open the link in a new tab

**Comment by advocatux** [comment]
It is not just an issue with github, it's the browser doesn't show a context menu when pressing & holding any link

**Comment by nfsprodriver** [comment]
A qt module QtQuick.Controls is missing in Ubuntu Touch image. To install it run `sudo apt install qml-module-qtquick-controls` . For now context menu looks fancy (new window overlay), but it seems to work.

**Comment by doniks** [comment]
fixed
