### ISSUE TITLE
webapp-container: Block pop-ups

### ISSUE THREAD

**Issue by gmelchett** [ubports/morph-browser#91]
A feature suggestion: 

Be able configure block pop-up windows in webapps.

**Comment by balcy** [comment]
good suggestion, there is even a popupBlockerEnabled property (which is on by default), but it seems not to be used for external urls right now.

**Comment by balcy** [comment]
do you have an example webapp with popup windows ?

**Comment by stekalb** [comment]
A really bad one is currently one of my webapps: [https://open-store.io/manage/20minch.ste-kal](20min.ch) - It triggers at least twitter and facebook popups. Which I would to prefer blocked by the webapp container.

**Comment by gmelchett** [comment]
Thanks for looking into this!

This webapp [SVT TextTv](http://lithops.se/svttextv.gmelchett_0.1_all.click) behaves badly together with uAdBlocker on Ubports version 23. (Nexus 5)
For every link (numbered) clicked on, one to close to ten, pop-up windows with link to doubleclick-something shows up in morph.

A odd side effect is that after around 30 open empty tabs the phone GUI freezes.
First I though it ran out of memory, but that is not the case (had a look over adb) kill off morph + QtWebEngine didn't help anything.

**Comment by balcy** [comment]
there was one mistake that led to open requests that are actually for the same page in morph. (so those are not popups but requests for the same page)
this was corrected in https://github.com/ubports/morph-browser/pull/84 (not yet merged)

**Comment by balcy** [comment]
for testing you can replace the qml file on the device https://github.com/ubports/morph-browser/blob/dec570a5ac6aec5637fbb8d93fdca3c2d8e91f00/src/app/webcontainer/WebViewImplOxide.qml

**Comment by stekalb** [comment]
Where shall the file be placed on the device? Or would I need to recompile morph?

**Comment by balcy** [comment]
`/usr/share/morph-browser/webcontainer` (requires rw image `sudo mount -o remount,rw /`), recompile is not needed

**Comment by stekalb** [comment]
thanks. Works for 20min.ch

**Comment by stekalb** [comment]
seems also to work for svt texttv as far as I can tell.

**Comment by gmelchett** [comment]
Yes, it works fine for svt texttv as well! Thanks you!
