### ISSUE TITLE
print to pdf function

### ISSUE THREAD

**Issue by mateosalta** [ubports/morph-browser#95]
I noticed in the docs, qtwebengine has a print to pdf function https://doc.qt.io/qt-5.9/qtwebengine-features.html#print-to-pdf

And was wondering if this would be something we could make use of.

**Comment by balcy** [comment]
yes I travelled to the past and created this PR :)
https://github.com/ubports/morph-browser/pull/89

**Comment by balcy** [comment]
the current implementation does always print A4 Portrait format, maybe later we need a selectable format.

**Comment by mateosalta** [comment]
wow nice 3 days ago! awesome work!

**Comment by mateosalta** [comment]
wow nice 3 days ago! awesome work!

**Comment by Flohack74** [comment]
Note also that the ubports printing stack will come in handy once its working. It can then also print PDFs to real printers ^^

**Comment by UniversalSuperBox** [comment]
The PR has not yet been merged, this issue is not closed yet.
